// Code generated by ent, DO NOT EDIT.

package knowledgebase

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the knowledgebase type in the database.
	Label = "knowledge_base"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldChunkStrategy holds the string denoting the chunk_strategy field in the database.
	FieldChunkStrategy = "chunk_strategy"
	// FieldChunkSize holds the string denoting the chunk_size field in the database.
	FieldChunkSize = "chunk_size"
	// FieldChunkOverlap holds the string denoting the chunk_overlap field in the database.
	FieldChunkOverlap = "chunk_overlap"
	// FieldChunkSeparatorsJSON holds the string denoting the chunk_separators_json field in the database.
	FieldChunkSeparatorsJSON = "chunk_separators_json"
	// FieldEnableParentChild holds the string denoting the enable_parent_child field in the database.
	FieldEnableParentChild = "enable_parent_child"
	// FieldParentChunkSize holds the string denoting the parent_chunk_size field in the database.
	FieldParentChunkSize = "parent_chunk_size"
	// FieldChildChunkSize holds the string denoting the child_chunk_size field in the database.
	FieldChildChunkSize = "child_chunk_size"
	// FieldChatModelID holds the string denoting the chat_model_id field in the database.
	FieldChatModelID = "chat_model_id"
	// FieldEmbeddingModelID holds the string denoting the embedding_model_id field in the database.
	FieldEmbeddingModelID = "embedding_model_id"
	// FieldRerankModelID holds the string denoting the rerank_model_id field in the database.
	FieldRerankModelID = "rerank_model_id"
	// FieldWikiEnabled holds the string denoting the wiki_enabled field in the database.
	FieldWikiEnabled = "wiki_enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the knowledgebase in the database.
	Table = "petrichor_kb_knowledge_base"
)

// Columns holds all SQL columns for knowledgebase fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldName,
	FieldDescription,
	FieldChunkStrategy,
	FieldChunkSize,
	FieldChunkOverlap,
	FieldChunkSeparatorsJSON,
	FieldEnableParentChild,
	FieldParentChunkSize,
	FieldChildChunkSize,
	FieldChatModelID,
	FieldEmbeddingModelID,
	FieldRerankModelID,
	FieldWikiEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultChunkStrategy holds the default value on creation for the "chunk_strategy" field.
	DefaultChunkStrategy string
	// DefaultChunkSize holds the default value on creation for the "chunk_size" field.
	DefaultChunkSize int
	// DefaultChunkOverlap holds the default value on creation for the "chunk_overlap" field.
	DefaultChunkOverlap int
	// DefaultEnableParentChild holds the default value on creation for the "enable_parent_child" field.
	DefaultEnableParentChild bool
	// DefaultParentChunkSize holds the default value on creation for the "parent_chunk_size" field.
	DefaultParentChunkSize int
	// DefaultChildChunkSize holds the default value on creation for the "child_chunk_size" field.
	DefaultChildChunkSize int
	// DefaultWikiEnabled holds the default value on creation for the "wiki_enabled" field.
	DefaultWikiEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the KnowledgeBase queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByChunkStrategy orders the results by the chunk_strategy field.
func ByChunkStrategy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkStrategy, opts...).ToFunc()
}

// ByChunkSize orders the results by the chunk_size field.
func ByChunkSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkSize, opts...).ToFunc()
}

// ByChunkOverlap orders the results by the chunk_overlap field.
func ByChunkOverlap(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkOverlap, opts...).ToFunc()
}

// ByChunkSeparatorsJSON orders the results by the chunk_separators_json field.
func ByChunkSeparatorsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkSeparatorsJSON, opts...).ToFunc()
}

// ByEnableParentChild orders the results by the enable_parent_child field.
func ByEnableParentChild(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnableParentChild, opts...).ToFunc()
}

// ByParentChunkSize orders the results by the parent_chunk_size field.
func ByParentChunkSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentChunkSize, opts...).ToFunc()
}

// ByChildChunkSize orders the results by the child_chunk_size field.
func ByChildChunkSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChildChunkSize, opts...).ToFunc()
}

// ByChatModelID orders the results by the chat_model_id field.
func ByChatModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatModelID, opts...).ToFunc()
}

// ByEmbeddingModelID orders the results by the embedding_model_id field.
func ByEmbeddingModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmbeddingModelID, opts...).ToFunc()
}

// ByRerankModelID orders the results by the rerank_model_id field.
func ByRerankModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRerankModelID, opts...).ToFunc()
}

// ByWikiEnabled orders the results by the wiki_enabled field.
func ByWikiEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWikiEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
