// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ciao1019/Petrichor/apps/api/ent/agentapikey"
)

// AgentAPIKeyCreate is the builder for creating a AgentAPIKey entity.
type AgentAPIKeyCreate struct {
	config
	mutation *AgentAPIKeyMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *AgentAPIKeyCreate) SetUserID(v int64) *AgentAPIKeyCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AgentAPIKeyCreate) SetName(v string) *AgentAPIKeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKeyHash sets the "key_hash" field.
func (_c *AgentAPIKeyCreate) SetKeyHash(v string) *AgentAPIKeyCreate {
	_c.mutation.SetKeyHash(v)
	return _c
}

// SetKeyPrefix sets the "key_prefix" field.
func (_c *AgentAPIKeyCreate) SetKeyPrefix(v string) *AgentAPIKeyCreate {
	_c.mutation.SetKeyPrefix(v)
	return _c
}

// SetScopesJSON sets the "scopes_json" field.
func (_c *AgentAPIKeyCreate) SetScopesJSON(v string) *AgentAPIKeyCreate {
	_c.mutation.SetScopesJSON(v)
	return _c
}

// SetNillableScopesJSON sets the "scopes_json" field if the given value is not nil.
func (_c *AgentAPIKeyCreate) SetNillableScopesJSON(v *string) *AgentAPIKeyCreate {
	if v != nil {
		_c.SetScopesJSON(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AgentAPIKeyCreate) SetExpiresAt(v time.Time) *AgentAPIKeyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *AgentAPIKeyCreate) SetNillableExpiresAt(v *time.Time) *AgentAPIKeyCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *AgentAPIKeyCreate) SetLastUsedAt(v time.Time) *AgentAPIKeyCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *AgentAPIKeyCreate) SetNillableLastUsedAt(v *time.Time) *AgentAPIKeyCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *AgentAPIKeyCreate) SetRevokedAt(v time.Time) *AgentAPIKeyCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *AgentAPIKeyCreate) SetNillableRevokedAt(v *time.Time) *AgentAPIKeyCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentAPIKeyCreate) SetCreatedAt(v time.Time) *AgentAPIKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentAPIKeyCreate) SetNillableCreatedAt(v *time.Time) *AgentAPIKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentAPIKeyCreate) SetUpdatedAt(v time.Time) *AgentAPIKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentAPIKeyCreate) SetNillableUpdatedAt(v *time.Time) *AgentAPIKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentAPIKeyCreate) SetID(v int64) *AgentAPIKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AgentAPIKeyMutation object of the builder.
func (_c *AgentAPIKeyCreate) Mutation() *AgentAPIKeyMutation {
	return _c.mutation
}

// Save creates the AgentAPIKey in the database.
func (_c *AgentAPIKeyCreate) Save(ctx context.Context) (*AgentAPIKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentAPIKeyCreate) SaveX(ctx context.Context) *AgentAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentAPIKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentAPIKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentAPIKeyCreate) defaults() {
	if _, ok := _c.mutation.ScopesJSON(); !ok {
		v := agentapikey.DefaultScopesJSON
		_c.mutation.SetScopesJSON(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agentapikey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agentapikey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentAPIKeyCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AgentAPIKey.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AgentAPIKey.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := agentapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentAPIKey.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyHash(); !ok {
		return &ValidationError{Name: "key_hash", err: errors.New(`ent: missing required field "AgentAPIKey.key_hash"`)}
	}
	if v, ok := _c.mutation.KeyHash(); ok {
		if err := agentapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "AgentAPIKey.key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyPrefix(); !ok {
		return &ValidationError{Name: "key_prefix", err: errors.New(`ent: missing required field "AgentAPIKey.key_prefix"`)}
	}
	if v, ok := _c.mutation.KeyPrefix(); ok {
		if err := agentapikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "AgentAPIKey.key_prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopesJSON(); !ok {
		return &ValidationError{Name: "scopes_json", err: errors.New(`ent: missing required field "AgentAPIKey.scopes_json"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentAPIKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AgentAPIKey.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := agentapikey.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AgentAPIKey.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AgentAPIKeyCreate) sqlSave(ctx context.Context) (*AgentAPIKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentAPIKeyCreate) createSpec() (*AgentAPIKey, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentAPIKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentapikey.Table, sqlgraph.NewFieldSpec(agentapikey.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(agentapikey.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(agentapikey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.KeyHash(); ok {
		_spec.SetField(agentapikey.FieldKeyHash, field.TypeString, value)
		_node.KeyHash = value
	}
	if value, ok := _c.mutation.KeyPrefix(); ok {
		_spec.SetField(agentapikey.FieldKeyPrefix, field.TypeString, value)
		_node.KeyPrefix = value
	}
	if value, ok := _c.mutation.ScopesJSON(); ok {
		_spec.SetField(agentapikey.FieldScopesJSON, field.TypeString, value)
		_node.ScopesJSON = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(agentapikey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(agentapikey.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(agentapikey.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentapikey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agentapikey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AgentAPIKeyCreateBulk is the builder for creating many AgentAPIKey entities in bulk.
type AgentAPIKeyCreateBulk struct {
	config
	err      error
	builders []*AgentAPIKeyCreate
}

// Save creates the AgentAPIKey entities in the database.
func (_c *AgentAPIKeyCreateBulk) Save(ctx context.Context) ([]*AgentAPIKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentAPIKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentAPIKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentAPIKeyCreateBulk) SaveX(ctx context.Context) []*AgentAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentAPIKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentAPIKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
