// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ciao1019/Petrichor/apps/api/ent/agentcalllog"
)

// AgentCallLogCreate is the builder for creating a AgentCallLog entity.
type AgentCallLogCreate struct {
	config
	mutation *AgentCallLogMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *AgentCallLogCreate) SetUserID(v int64) *AgentCallLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *AgentCallLogCreate) SetAPIKeyID(v int64) *AgentCallLogCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetAPIKeyPrefix sets the "api_key_prefix" field.
func (_c *AgentCallLogCreate) SetAPIKeyPrefix(v string) *AgentCallLogCreate {
	_c.mutation.SetAPIKeyPrefix(v)
	return _c
}

// SetMethod sets the "method" field.
func (_c *AgentCallLogCreate) SetMethod(v string) *AgentCallLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *AgentCallLogCreate) SetPath(v string) *AgentCallLogCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *AgentCallLogCreate) SetIP(v string) *AgentCallLogCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *AgentCallLogCreate) SetNillableIP(v *string) *AgentCallLogCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *AgentCallLogCreate) SetUserAgent(v string) *AgentCallLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *AgentCallLogCreate) SetNillableUserAgent(v *string) *AgentCallLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetRequestJSON sets the "request_json" field.
func (_c *AgentCallLogCreate) SetRequestJSON(v string) *AgentCallLogCreate {
	_c.mutation.SetRequestJSON(v)
	return _c
}

// SetNillableRequestJSON sets the "request_json" field if the given value is not nil.
func (_c *AgentCallLogCreate) SetNillableRequestJSON(v *string) *AgentCallLogCreate {
	if v != nil {
		_c.SetRequestJSON(*v)
	}
	return _c
}

// SetResponseJSON sets the "response_json" field.
func (_c *AgentCallLogCreate) SetResponseJSON(v string) *AgentCallLogCreate {
	_c.mutation.SetResponseJSON(v)
	return _c
}

// SetNillableResponseJSON sets the "response_json" field if the given value is not nil.
func (_c *AgentCallLogCreate) SetNillableResponseJSON(v *string) *AgentCallLogCreate {
	if v != nil {
		_c.SetResponseJSON(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *AgentCallLogCreate) SetStatusCode(v int) *AgentCallLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *AgentCallLogCreate) SetDurationMs(v int) *AgentCallLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *AgentCallLogCreate) SetErrorMessage(v string) *AgentCallLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *AgentCallLogCreate) SetNillableErrorMessage(v *string) *AgentCallLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentCallLogCreate) SetCreatedAt(v time.Time) *AgentCallLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentCallLogCreate) SetNillableCreatedAt(v *time.Time) *AgentCallLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentCallLogCreate) SetID(v int64) *AgentCallLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AgentCallLogMutation object of the builder.
func (_c *AgentCallLogCreate) Mutation() *AgentCallLogMutation {
	return _c.mutation
}

// Save creates the AgentCallLog in the database.
func (_c *AgentCallLogCreate) Save(ctx context.Context) (*AgentCallLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentCallLogCreate) SaveX(ctx context.Context) *AgentCallLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCallLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCallLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentCallLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agentcalllog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentCallLogCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AgentCallLog.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "AgentCallLog.api_key_id"`)}
	}
	if _, ok := _c.mutation.APIKeyPrefix(); !ok {
		return &ValidationError{Name: "api_key_prefix", err: errors.New(`ent: missing required field "AgentCallLog.api_key_prefix"`)}
	}
	if v, ok := _c.mutation.APIKeyPrefix(); ok {
		if err := agentcalllog.APIKeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "api_key_prefix", err: fmt.Errorf(`ent: validator failed for field "AgentCallLog.api_key_prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "AgentCallLog.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := agentcalllog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "AgentCallLog.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "AgentCallLog.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := agentcalllog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AgentCallLog.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "AgentCallLog.status_code"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "AgentCallLog.duration_ms"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentCallLog.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := agentcalllog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AgentCallLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AgentCallLogCreate) sqlSave(ctx context.Context) (*AgentCallLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentCallLogCreate) createSpec() (*AgentCallLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentCallLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentcalllog.Table, sqlgraph.NewFieldSpec(agentcalllog.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(agentcalllog.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(agentcalllog.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.APIKeyPrefix(); ok {
		_spec.SetField(agentcalllog.FieldAPIKeyPrefix, field.TypeString, value)
		_node.APIKeyPrefix = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(agentcalllog.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(agentcalllog.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(agentcalllog.FieldIP, field.TypeString, value)
		_node.IP = &value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(agentcalllog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := _c.mutation.RequestJSON(); ok {
		_spec.SetField(agentcalllog.FieldRequestJSON, field.TypeString, value)
		_node.RequestJSON = &value
	}
	if value, ok := _c.mutation.ResponseJSON(); ok {
		_spec.SetField(agentcalllog.FieldResponseJSON, field.TypeString, value)
		_node.ResponseJSON = &value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(agentcalllog.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(agentcalllog.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(agentcalllog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentcalllog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AgentCallLogCreateBulk is the builder for creating many AgentCallLog entities in bulk.
type AgentCallLogCreateBulk struct {
	config
	err      error
	builders []*AgentCallLogCreate
}

// Save creates the AgentCallLog entities in the database.
func (_c *AgentCallLogCreateBulk) Save(ctx context.Context) ([]*AgentCallLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentCallLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentCallLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentCallLogCreateBulk) SaveX(ctx context.Context) []*AgentCallLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCallLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCallLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
