// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ciao1019/Petrichor/apps/api/ent/agentapikey"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// AgentAPIKeyUpdate is the builder for updating AgentAPIKey entities.
type AgentAPIKeyUpdate struct {
	config
	hooks    []Hook
	mutation *AgentAPIKeyMutation
}

// Where appends a list predicates to the AgentAPIKeyUpdate builder.
func (_u *AgentAPIKeyUpdate) Where(ps ...predicate.AgentAPIKey) *AgentAPIKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AgentAPIKeyUpdate) SetUserID(v int64) *AgentAPIKeyUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AgentAPIKeyUpdate) SetNillableUserID(v *int64) *AgentAPIKeyUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AgentAPIKeyUpdate) AddUserID(v int64) *AgentAPIKeyUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AgentAPIKeyUpdate) SetName(v string) *AgentAPIKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentAPIKeyUpdate) SetNillableName(v *string) *AgentAPIKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *AgentAPIKeyUpdate) SetKeyHash(v string) *AgentAPIKeyUpdate {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *AgentAPIKeyUpdate) SetNillableKeyHash(v *string) *AgentAPIKeyUpdate {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *AgentAPIKeyUpdate) SetKeyPrefix(v string) *AgentAPIKeyUpdate {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *AgentAPIKeyUpdate) SetNillableKeyPrefix(v *string) *AgentAPIKeyUpdate {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// SetScopesJSON sets the "scopes_json" field.
func (_u *AgentAPIKeyUpdate) SetScopesJSON(v string) *AgentAPIKeyUpdate {
	_u.mutation.SetScopesJSON(v)
	return _u
}

// SetNillableScopesJSON sets the "scopes_json" field if the given value is not nil.
func (_u *AgentAPIKeyUpdate) SetNillableScopesJSON(v *string) *AgentAPIKeyUpdate {
	if v != nil {
		_u.SetScopesJSON(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AgentAPIKeyUpdate) SetExpiresAt(v time.Time) *AgentAPIKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AgentAPIKeyUpdate) SetNillableExpiresAt(v *time.Time) *AgentAPIKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AgentAPIKeyUpdate) ClearExpiresAt() *AgentAPIKeyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AgentAPIKeyUpdate) SetLastUsedAt(v time.Time) *AgentAPIKeyUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AgentAPIKeyUpdate) SetNillableLastUsedAt(v *time.Time) *AgentAPIKeyUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AgentAPIKeyUpdate) ClearLastUsedAt() *AgentAPIKeyUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AgentAPIKeyUpdate) SetRevokedAt(v time.Time) *AgentAPIKeyUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AgentAPIKeyUpdate) SetNillableRevokedAt(v *time.Time) *AgentAPIKeyUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AgentAPIKeyUpdate) ClearRevokedAt() *AgentAPIKeyUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentAPIKeyUpdate) SetUpdatedAt(v time.Time) *AgentAPIKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AgentAPIKeyMutation object of the builder.
func (_u *AgentAPIKeyUpdate) Mutation() *AgentAPIKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentAPIKeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentAPIKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentAPIKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentAPIKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentAPIKeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentAPIKeyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := agentapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentAPIKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := agentapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "AgentAPIKey.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyPrefix(); ok {
		if err := agentapikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "AgentAPIKey.key_prefix": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentAPIKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentapikey.Table, agentapikey.Columns, sqlgraph.NewFieldSpec(agentapikey.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(agentapikey.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(agentapikey.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(agentapikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(agentapikey.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopesJSON(); ok {
		_spec.SetField(agentapikey.FieldScopesJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(agentapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(agentapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(agentapikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(agentapikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(agentapikey.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(agentapikey.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentAPIKeyUpdateOne is the builder for updating a single AgentAPIKey entity.
type AgentAPIKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentAPIKeyMutation
}

// SetUserID sets the "user_id" field.
func (_u *AgentAPIKeyUpdateOne) SetUserID(v int64) *AgentAPIKeyUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AgentAPIKeyUpdateOne) SetNillableUserID(v *int64) *AgentAPIKeyUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AgentAPIKeyUpdateOne) AddUserID(v int64) *AgentAPIKeyUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AgentAPIKeyUpdateOne) SetName(v string) *AgentAPIKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentAPIKeyUpdateOne) SetNillableName(v *string) *AgentAPIKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *AgentAPIKeyUpdateOne) SetKeyHash(v string) *AgentAPIKeyUpdateOne {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *AgentAPIKeyUpdateOne) SetNillableKeyHash(v *string) *AgentAPIKeyUpdateOne {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *AgentAPIKeyUpdateOne) SetKeyPrefix(v string) *AgentAPIKeyUpdateOne {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *AgentAPIKeyUpdateOne) SetNillableKeyPrefix(v *string) *AgentAPIKeyUpdateOne {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// SetScopesJSON sets the "scopes_json" field.
func (_u *AgentAPIKeyUpdateOne) SetScopesJSON(v string) *AgentAPIKeyUpdateOne {
	_u.mutation.SetScopesJSON(v)
	return _u
}

// SetNillableScopesJSON sets the "scopes_json" field if the given value is not nil.
func (_u *AgentAPIKeyUpdateOne) SetNillableScopesJSON(v *string) *AgentAPIKeyUpdateOne {
	if v != nil {
		_u.SetScopesJSON(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AgentAPIKeyUpdateOne) SetExpiresAt(v time.Time) *AgentAPIKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AgentAPIKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *AgentAPIKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AgentAPIKeyUpdateOne) ClearExpiresAt() *AgentAPIKeyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AgentAPIKeyUpdateOne) SetLastUsedAt(v time.Time) *AgentAPIKeyUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AgentAPIKeyUpdateOne) SetNillableLastUsedAt(v *time.Time) *AgentAPIKeyUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AgentAPIKeyUpdateOne) ClearLastUsedAt() *AgentAPIKeyUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AgentAPIKeyUpdateOne) SetRevokedAt(v time.Time) *AgentAPIKeyUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AgentAPIKeyUpdateOne) SetNillableRevokedAt(v *time.Time) *AgentAPIKeyUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AgentAPIKeyUpdateOne) ClearRevokedAt() *AgentAPIKeyUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentAPIKeyUpdateOne) SetUpdatedAt(v time.Time) *AgentAPIKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AgentAPIKeyMutation object of the builder.
func (_u *AgentAPIKeyUpdateOne) Mutation() *AgentAPIKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentAPIKeyUpdate builder.
func (_u *AgentAPIKeyUpdateOne) Where(ps ...predicate.AgentAPIKey) *AgentAPIKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentAPIKeyUpdateOne) Select(field string, fields ...string) *AgentAPIKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentAPIKey entity.
func (_u *AgentAPIKeyUpdateOne) Save(ctx context.Context) (*AgentAPIKey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentAPIKeyUpdateOne) SaveX(ctx context.Context) *AgentAPIKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentAPIKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentAPIKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentAPIKeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentAPIKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := agentapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentAPIKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := agentapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "AgentAPIKey.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyPrefix(); ok {
		if err := agentapikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "AgentAPIKey.key_prefix": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentAPIKeyUpdateOne) sqlSave(ctx context.Context) (_node *AgentAPIKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentapikey.Table, agentapikey.Columns, sqlgraph.NewFieldSpec(agentapikey.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentAPIKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentapikey.FieldID)
		for _, f := range fields {
			if !agentapikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(agentapikey.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(agentapikey.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(agentapikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(agentapikey.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopesJSON(); ok {
		_spec.SetField(agentapikey.FieldScopesJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(agentapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(agentapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(agentapikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(agentapikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(agentapikey.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(agentapikey.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AgentAPIKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
