// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Ciao1019/Petrichor/apps/api/ent/assistantthread"
)

// AssistantThread is the model entity for the AssistantThread schema.
type AssistantThread struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// FocusJSON holds the value of the "focus_json" field.
	FocusJSON *string `json:"focus_json,omitempty"`
	// ContextSummaryMd holds the value of the "context_summary_md" field.
	ContextSummaryMd *string `json:"context_summary_md,omitempty"`
	// ContextSummaryUntilMessageID holds the value of the "context_summary_until_message_id" field.
	ContextSummaryUntilMessageID *int64 `json:"context_summary_until_message_id,omitempty"`
	// ContextSummaryUpdatedAt holds the value of the "context_summary_updated_at" field.
	ContextSummaryUpdatedAt *time.Time `json:"context_summary_updated_at,omitempty"`
	// DangerAllowlistJSON holds the value of the "danger_allowlist_json" field.
	DangerAllowlistJSON *string `json:"danger_allowlist_json,omitempty"`
	// OperatorMemorySnapshotJSON holds the value of the "operator_memory_snapshot_json" field.
	OperatorMemorySnapshotJSON *string `json:"operator_memory_snapshot_json,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt    *time.Time `json:"deleted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AssistantThread) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case assistantthread.FieldID, assistantthread.FieldUserID, assistantthread.FieldContextSummaryUntilMessageID:
			values[i] = new(sql.NullInt64)
		case assistantthread.FieldTitle, assistantthread.FieldFocusJSON, assistantthread.FieldContextSummaryMd, assistantthread.FieldDangerAllowlistJSON, assistantthread.FieldOperatorMemorySnapshotJSON:
			values[i] = new(sql.NullString)
		case assistantthread.FieldContextSummaryUpdatedAt, assistantthread.FieldCreatedAt, assistantthread.FieldUpdatedAt, assistantthread.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AssistantThread fields.
func (_m *AssistantThread) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case assistantthread.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case assistantthread.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case assistantthread.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case assistantthread.FieldFocusJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field focus_json", values[i])
			} else if value.Valid {
				_m.FocusJSON = new(string)
				*_m.FocusJSON = value.String
			}
		case assistantthread.FieldContextSummaryMd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context_summary_md", values[i])
			} else if value.Valid {
				_m.ContextSummaryMd = new(string)
				*_m.ContextSummaryMd = value.String
			}
		case assistantthread.FieldContextSummaryUntilMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field context_summary_until_message_id", values[i])
			} else if value.Valid {
				_m.ContextSummaryUntilMessageID = new(int64)
				*_m.ContextSummaryUntilMessageID = value.Int64
			}
		case assistantthread.FieldContextSummaryUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field context_summary_updated_at", values[i])
			} else if value.Valid {
				_m.ContextSummaryUpdatedAt = new(time.Time)
				*_m.ContextSummaryUpdatedAt = value.Time
			}
		case assistantthread.FieldDangerAllowlistJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field danger_allowlist_json", values[i])
			} else if value.Valid {
				_m.DangerAllowlistJSON = new(string)
				*_m.DangerAllowlistJSON = value.String
			}
		case assistantthread.FieldOperatorMemorySnapshotJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator_memory_snapshot_json", values[i])
			} else if value.Valid {
				_m.OperatorMemorySnapshotJSON = new(string)
				*_m.OperatorMemorySnapshotJSON = value.String
			}
		case assistantthread.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case assistantthread.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case assistantthread.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AssistantThread.
// This includes values selected through modifiers, order, etc.
func (_m *AssistantThread) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AssistantThread.
// Note that you need to call AssistantThread.Unwrap() before calling this method if this AssistantThread
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AssistantThread) Update() *AssistantThreadUpdateOne {
	return NewAssistantThreadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AssistantThread entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AssistantThread) Unwrap() *AssistantThread {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AssistantThread is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AssistantThread) String() string {
	var builder strings.Builder
	builder.WriteString("AssistantThread(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.FocusJSON; v != nil {
		builder.WriteString("focus_json=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ContextSummaryMd; v != nil {
		builder.WriteString("context_summary_md=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ContextSummaryUntilMessageID; v != nil {
		builder.WriteString("context_summary_until_message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ContextSummaryUpdatedAt; v != nil {
		builder.WriteString("context_summary_updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DangerAllowlistJSON; v != nil {
		builder.WriteString("danger_allowlist_json=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OperatorMemorySnapshotJSON; v != nil {
		builder.WriteString("operator_memory_snapshot_json=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AssistantThreads is a parsable slice of AssistantThread.
type AssistantThreads []*AssistantThread
