// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ciao1019/Petrichor/apps/api/ent/assistantthread"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// AssistantThreadUpdate is the builder for updating AssistantThread entities.
type AssistantThreadUpdate struct {
	config
	hooks    []Hook
	mutation *AssistantThreadMutation
}

// Where appends a list predicates to the AssistantThreadUpdate builder.
func (_u *AssistantThreadUpdate) Where(ps ...predicate.AssistantThread) *AssistantThreadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AssistantThreadUpdate) SetUserID(v int64) *AssistantThreadUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AssistantThreadUpdate) SetNillableUserID(v *int64) *AssistantThreadUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AssistantThreadUpdate) AddUserID(v int64) *AssistantThreadUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *AssistantThreadUpdate) SetTitle(v string) *AssistantThreadUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AssistantThreadUpdate) SetNillableTitle(v *string) *AssistantThreadUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetFocusJSON sets the "focus_json" field.
func (_u *AssistantThreadUpdate) SetFocusJSON(v string) *AssistantThreadUpdate {
	_u.mutation.SetFocusJSON(v)
	return _u
}

// SetNillableFocusJSON sets the "focus_json" field if the given value is not nil.
func (_u *AssistantThreadUpdate) SetNillableFocusJSON(v *string) *AssistantThreadUpdate {
	if v != nil {
		_u.SetFocusJSON(*v)
	}
	return _u
}

// ClearFocusJSON clears the value of the "focus_json" field.
func (_u *AssistantThreadUpdate) ClearFocusJSON() *AssistantThreadUpdate {
	_u.mutation.ClearFocusJSON()
	return _u
}

// SetContextSummaryMd sets the "context_summary_md" field.
func (_u *AssistantThreadUpdate) SetContextSummaryMd(v string) *AssistantThreadUpdate {
	_u.mutation.SetContextSummaryMd(v)
	return _u
}

// SetNillableContextSummaryMd sets the "context_summary_md" field if the given value is not nil.
func (_u *AssistantThreadUpdate) SetNillableContextSummaryMd(v *string) *AssistantThreadUpdate {
	if v != nil {
		_u.SetContextSummaryMd(*v)
	}
	return _u
}

// ClearContextSummaryMd clears the value of the "context_summary_md" field.
func (_u *AssistantThreadUpdate) ClearContextSummaryMd() *AssistantThreadUpdate {
	_u.mutation.ClearContextSummaryMd()
	return _u
}

// SetContextSummaryUntilMessageID sets the "context_summary_until_message_id" field.
func (_u *AssistantThreadUpdate) SetContextSummaryUntilMessageID(v int64) *AssistantThreadUpdate {
	_u.mutation.ResetContextSummaryUntilMessageID()
	_u.mutation.SetContextSummaryUntilMessageID(v)
	return _u
}

// SetNillableContextSummaryUntilMessageID sets the "context_summary_until_message_id" field if the given value is not nil.
func (_u *AssistantThreadUpdate) SetNillableContextSummaryUntilMessageID(v *int64) *AssistantThreadUpdate {
	if v != nil {
		_u.SetContextSummaryUntilMessageID(*v)
	}
	return _u
}

// AddContextSummaryUntilMessageID adds value to the "context_summary_until_message_id" field.
func (_u *AssistantThreadUpdate) AddContextSummaryUntilMessageID(v int64) *AssistantThreadUpdate {
	_u.mutation.AddContextSummaryUntilMessageID(v)
	return _u
}

// ClearContextSummaryUntilMessageID clears the value of the "context_summary_until_message_id" field.
func (_u *AssistantThreadUpdate) ClearContextSummaryUntilMessageID() *AssistantThreadUpdate {
	_u.mutation.ClearContextSummaryUntilMessageID()
	return _u
}

// SetContextSummaryUpdatedAt sets the "context_summary_updated_at" field.
func (_u *AssistantThreadUpdate) SetContextSummaryUpdatedAt(v time.Time) *AssistantThreadUpdate {
	_u.mutation.SetContextSummaryUpdatedAt(v)
	return _u
}

// SetNillableContextSummaryUpdatedAt sets the "context_summary_updated_at" field if the given value is not nil.
func (_u *AssistantThreadUpdate) SetNillableContextSummaryUpdatedAt(v *time.Time) *AssistantThreadUpdate {
	if v != nil {
		_u.SetContextSummaryUpdatedAt(*v)
	}
	return _u
}

// ClearContextSummaryUpdatedAt clears the value of the "context_summary_updated_at" field.
func (_u *AssistantThreadUpdate) ClearContextSummaryUpdatedAt() *AssistantThreadUpdate {
	_u.mutation.ClearContextSummaryUpdatedAt()
	return _u
}

// SetDangerAllowlistJSON sets the "danger_allowlist_json" field.
func (_u *AssistantThreadUpdate) SetDangerAllowlistJSON(v string) *AssistantThreadUpdate {
	_u.mutation.SetDangerAllowlistJSON(v)
	return _u
}

// SetNillableDangerAllowlistJSON sets the "danger_allowlist_json" field if the given value is not nil.
func (_u *AssistantThreadUpdate) SetNillableDangerAllowlistJSON(v *string) *AssistantThreadUpdate {
	if v != nil {
		_u.SetDangerAllowlistJSON(*v)
	}
	return _u
}

// ClearDangerAllowlistJSON clears the value of the "danger_allowlist_json" field.
func (_u *AssistantThreadUpdate) ClearDangerAllowlistJSON() *AssistantThreadUpdate {
	_u.mutation.ClearDangerAllowlistJSON()
	return _u
}

// SetOperatorMemorySnapshotJSON sets the "operator_memory_snapshot_json" field.
func (_u *AssistantThreadUpdate) SetOperatorMemorySnapshotJSON(v string) *AssistantThreadUpdate {
	_u.mutation.SetOperatorMemorySnapshotJSON(v)
	return _u
}

// SetNillableOperatorMemorySnapshotJSON sets the "operator_memory_snapshot_json" field if the given value is not nil.
func (_u *AssistantThreadUpdate) SetNillableOperatorMemorySnapshotJSON(v *string) *AssistantThreadUpdate {
	if v != nil {
		_u.SetOperatorMemorySnapshotJSON(*v)
	}
	return _u
}

// ClearOperatorMemorySnapshotJSON clears the value of the "operator_memory_snapshot_json" field.
func (_u *AssistantThreadUpdate) ClearOperatorMemorySnapshotJSON() *AssistantThreadUpdate {
	_u.mutation.ClearOperatorMemorySnapshotJSON()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssistantThreadUpdate) SetUpdatedAt(v time.Time) *AssistantThreadUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AssistantThreadUpdate) SetDeletedAt(v time.Time) *AssistantThreadUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AssistantThreadUpdate) SetNillableDeletedAt(v *time.Time) *AssistantThreadUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AssistantThreadUpdate) ClearDeletedAt() *AssistantThreadUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the AssistantThreadMutation object of the builder.
func (_u *AssistantThreadUpdate) Mutation() *AssistantThreadMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssistantThreadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssistantThreadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssistantThreadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssistantThreadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AssistantThreadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := assistantthread.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssistantThreadUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := assistantthread.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "AssistantThread.title": %w`, err)}
		}
	}
	return nil
}

func (_u *AssistantThreadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(assistantthread.Table, assistantthread.Columns, sqlgraph.NewFieldSpec(assistantthread.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(assistantthread.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(assistantthread.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(assistantthread.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.FocusJSON(); ok {
		_spec.SetField(assistantthread.FieldFocusJSON, field.TypeString, value)
	}
	if _u.mutation.FocusJSONCleared() {
		_spec.ClearField(assistantthread.FieldFocusJSON, field.TypeString)
	}
	if value, ok := _u.mutation.ContextSummaryMd(); ok {
		_spec.SetField(assistantthread.FieldContextSummaryMd, field.TypeString, value)
	}
	if _u.mutation.ContextSummaryMdCleared() {
		_spec.ClearField(assistantthread.FieldContextSummaryMd, field.TypeString)
	}
	if value, ok := _u.mutation.ContextSummaryUntilMessageID(); ok {
		_spec.SetField(assistantthread.FieldContextSummaryUntilMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedContextSummaryUntilMessageID(); ok {
		_spec.AddField(assistantthread.FieldContextSummaryUntilMessageID, field.TypeInt64, value)
	}
	if _u.mutation.ContextSummaryUntilMessageIDCleared() {
		_spec.ClearField(assistantthread.FieldContextSummaryUntilMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ContextSummaryUpdatedAt(); ok {
		_spec.SetField(assistantthread.FieldContextSummaryUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ContextSummaryUpdatedAtCleared() {
		_spec.ClearField(assistantthread.FieldContextSummaryUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DangerAllowlistJSON(); ok {
		_spec.SetField(assistantthread.FieldDangerAllowlistJSON, field.TypeString, value)
	}
	if _u.mutation.DangerAllowlistJSONCleared() {
		_spec.ClearField(assistantthread.FieldDangerAllowlistJSON, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorMemorySnapshotJSON(); ok {
		_spec.SetField(assistantthread.FieldOperatorMemorySnapshotJSON, field.TypeString, value)
	}
	if _u.mutation.OperatorMemorySnapshotJSONCleared() {
		_spec.ClearField(assistantthread.FieldOperatorMemorySnapshotJSON, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(assistantthread.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(assistantthread.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(assistantthread.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assistantthread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssistantThreadUpdateOne is the builder for updating a single AssistantThread entity.
type AssistantThreadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssistantThreadMutation
}

// SetUserID sets the "user_id" field.
func (_u *AssistantThreadUpdateOne) SetUserID(v int64) *AssistantThreadUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AssistantThreadUpdateOne) SetNillableUserID(v *int64) *AssistantThreadUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AssistantThreadUpdateOne) AddUserID(v int64) *AssistantThreadUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *AssistantThreadUpdateOne) SetTitle(v string) *AssistantThreadUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AssistantThreadUpdateOne) SetNillableTitle(v *string) *AssistantThreadUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetFocusJSON sets the "focus_json" field.
func (_u *AssistantThreadUpdateOne) SetFocusJSON(v string) *AssistantThreadUpdateOne {
	_u.mutation.SetFocusJSON(v)
	return _u
}

// SetNillableFocusJSON sets the "focus_json" field if the given value is not nil.
func (_u *AssistantThreadUpdateOne) SetNillableFocusJSON(v *string) *AssistantThreadUpdateOne {
	if v != nil {
		_u.SetFocusJSON(*v)
	}
	return _u
}

// ClearFocusJSON clears the value of the "focus_json" field.
func (_u *AssistantThreadUpdateOne) ClearFocusJSON() *AssistantThreadUpdateOne {
	_u.mutation.ClearFocusJSON()
	return _u
}

// SetContextSummaryMd sets the "context_summary_md" field.
func (_u *AssistantThreadUpdateOne) SetContextSummaryMd(v string) *AssistantThreadUpdateOne {
	_u.mutation.SetContextSummaryMd(v)
	return _u
}

// SetNillableContextSummaryMd sets the "context_summary_md" field if the given value is not nil.
func (_u *AssistantThreadUpdateOne) SetNillableContextSummaryMd(v *string) *AssistantThreadUpdateOne {
	if v != nil {
		_u.SetContextSummaryMd(*v)
	}
	return _u
}

// ClearContextSummaryMd clears the value of the "context_summary_md" field.
func (_u *AssistantThreadUpdateOne) ClearContextSummaryMd() *AssistantThreadUpdateOne {
	_u.mutation.ClearContextSummaryMd()
	return _u
}

// SetContextSummaryUntilMessageID sets the "context_summary_until_message_id" field.
func (_u *AssistantThreadUpdateOne) SetContextSummaryUntilMessageID(v int64) *AssistantThreadUpdateOne {
	_u.mutation.ResetContextSummaryUntilMessageID()
	_u.mutation.SetContextSummaryUntilMessageID(v)
	return _u
}

// SetNillableContextSummaryUntilMessageID sets the "context_summary_until_message_id" field if the given value is not nil.
func (_u *AssistantThreadUpdateOne) SetNillableContextSummaryUntilMessageID(v *int64) *AssistantThreadUpdateOne {
	if v != nil {
		_u.SetContextSummaryUntilMessageID(*v)
	}
	return _u
}

// AddContextSummaryUntilMessageID adds value to the "context_summary_until_message_id" field.
func (_u *AssistantThreadUpdateOne) AddContextSummaryUntilMessageID(v int64) *AssistantThreadUpdateOne {
	_u.mutation.AddContextSummaryUntilMessageID(v)
	return _u
}

// ClearContextSummaryUntilMessageID clears the value of the "context_summary_until_message_id" field.
func (_u *AssistantThreadUpdateOne) ClearContextSummaryUntilMessageID() *AssistantThreadUpdateOne {
	_u.mutation.ClearContextSummaryUntilMessageID()
	return _u
}

// SetContextSummaryUpdatedAt sets the "context_summary_updated_at" field.
func (_u *AssistantThreadUpdateOne) SetContextSummaryUpdatedAt(v time.Time) *AssistantThreadUpdateOne {
	_u.mutation.SetContextSummaryUpdatedAt(v)
	return _u
}

// SetNillableContextSummaryUpdatedAt sets the "context_summary_updated_at" field if the given value is not nil.
func (_u *AssistantThreadUpdateOne) SetNillableContextSummaryUpdatedAt(v *time.Time) *AssistantThreadUpdateOne {
	if v != nil {
		_u.SetContextSummaryUpdatedAt(*v)
	}
	return _u
}

// ClearContextSummaryUpdatedAt clears the value of the "context_summary_updated_at" field.
func (_u *AssistantThreadUpdateOne) ClearContextSummaryUpdatedAt() *AssistantThreadUpdateOne {
	_u.mutation.ClearContextSummaryUpdatedAt()
	return _u
}

// SetDangerAllowlistJSON sets the "danger_allowlist_json" field.
func (_u *AssistantThreadUpdateOne) SetDangerAllowlistJSON(v string) *AssistantThreadUpdateOne {
	_u.mutation.SetDangerAllowlistJSON(v)
	return _u
}

// SetNillableDangerAllowlistJSON sets the "danger_allowlist_json" field if the given value is not nil.
func (_u *AssistantThreadUpdateOne) SetNillableDangerAllowlistJSON(v *string) *AssistantThreadUpdateOne {
	if v != nil {
		_u.SetDangerAllowlistJSON(*v)
	}
	return _u
}

// ClearDangerAllowlistJSON clears the value of the "danger_allowlist_json" field.
func (_u *AssistantThreadUpdateOne) ClearDangerAllowlistJSON() *AssistantThreadUpdateOne {
	_u.mutation.ClearDangerAllowlistJSON()
	return _u
}

// SetOperatorMemorySnapshotJSON sets the "operator_memory_snapshot_json" field.
func (_u *AssistantThreadUpdateOne) SetOperatorMemorySnapshotJSON(v string) *AssistantThreadUpdateOne {
	_u.mutation.SetOperatorMemorySnapshotJSON(v)
	return _u
}

// SetNillableOperatorMemorySnapshotJSON sets the "operator_memory_snapshot_json" field if the given value is not nil.
func (_u *AssistantThreadUpdateOne) SetNillableOperatorMemorySnapshotJSON(v *string) *AssistantThreadUpdateOne {
	if v != nil {
		_u.SetOperatorMemorySnapshotJSON(*v)
	}
	return _u
}

// ClearOperatorMemorySnapshotJSON clears the value of the "operator_memory_snapshot_json" field.
func (_u *AssistantThreadUpdateOne) ClearOperatorMemorySnapshotJSON() *AssistantThreadUpdateOne {
	_u.mutation.ClearOperatorMemorySnapshotJSON()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssistantThreadUpdateOne) SetUpdatedAt(v time.Time) *AssistantThreadUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AssistantThreadUpdateOne) SetDeletedAt(v time.Time) *AssistantThreadUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AssistantThreadUpdateOne) SetNillableDeletedAt(v *time.Time) *AssistantThreadUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AssistantThreadUpdateOne) ClearDeletedAt() *AssistantThreadUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the AssistantThreadMutation object of the builder.
func (_u *AssistantThreadUpdateOne) Mutation() *AssistantThreadMutation {
	return _u.mutation
}

// Where appends a list predicates to the AssistantThreadUpdate builder.
func (_u *AssistantThreadUpdateOne) Where(ps ...predicate.AssistantThread) *AssistantThreadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssistantThreadUpdateOne) Select(field string, fields ...string) *AssistantThreadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AssistantThread entity.
func (_u *AssistantThreadUpdateOne) Save(ctx context.Context) (*AssistantThread, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssistantThreadUpdateOne) SaveX(ctx context.Context) *AssistantThread {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssistantThreadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssistantThreadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AssistantThreadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := assistantthread.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssistantThreadUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := assistantthread.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "AssistantThread.title": %w`, err)}
		}
	}
	return nil
}

func (_u *AssistantThreadUpdateOne) sqlSave(ctx context.Context) (_node *AssistantThread, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(assistantthread.Table, assistantthread.Columns, sqlgraph.NewFieldSpec(assistantthread.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AssistantThread.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assistantthread.FieldID)
		for _, f := range fields {
			if !assistantthread.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != assistantthread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(assistantthread.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(assistantthread.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(assistantthread.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.FocusJSON(); ok {
		_spec.SetField(assistantthread.FieldFocusJSON, field.TypeString, value)
	}
	if _u.mutation.FocusJSONCleared() {
		_spec.ClearField(assistantthread.FieldFocusJSON, field.TypeString)
	}
	if value, ok := _u.mutation.ContextSummaryMd(); ok {
		_spec.SetField(assistantthread.FieldContextSummaryMd, field.TypeString, value)
	}
	if _u.mutation.ContextSummaryMdCleared() {
		_spec.ClearField(assistantthread.FieldContextSummaryMd, field.TypeString)
	}
	if value, ok := _u.mutation.ContextSummaryUntilMessageID(); ok {
		_spec.SetField(assistantthread.FieldContextSummaryUntilMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedContextSummaryUntilMessageID(); ok {
		_spec.AddField(assistantthread.FieldContextSummaryUntilMessageID, field.TypeInt64, value)
	}
	if _u.mutation.ContextSummaryUntilMessageIDCleared() {
		_spec.ClearField(assistantthread.FieldContextSummaryUntilMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ContextSummaryUpdatedAt(); ok {
		_spec.SetField(assistantthread.FieldContextSummaryUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ContextSummaryUpdatedAtCleared() {
		_spec.ClearField(assistantthread.FieldContextSummaryUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DangerAllowlistJSON(); ok {
		_spec.SetField(assistantthread.FieldDangerAllowlistJSON, field.TypeString, value)
	}
	if _u.mutation.DangerAllowlistJSONCleared() {
		_spec.ClearField(assistantthread.FieldDangerAllowlistJSON, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorMemorySnapshotJSON(); ok {
		_spec.SetField(assistantthread.FieldOperatorMemorySnapshotJSON, field.TypeString, value)
	}
	if _u.mutation.OperatorMemorySnapshotJSONCleared() {
		_spec.ClearField(assistantthread.FieldOperatorMemorySnapshotJSON, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(assistantthread.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(assistantthread.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(assistantthread.FieldDeletedAt, field.TypeTime)
	}
	_node = &AssistantThread{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assistantthread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
