// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ciao1019/Petrichor/apps/api/ent/assistantconfirmation"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// AssistantConfirmationQuery is the builder for querying AssistantConfirmation entities.
type AssistantConfirmationQuery struct {
	config
	ctx        *QueryContext
	order      []assistantconfirmation.OrderOption
	inters     []Interceptor
	predicates []predicate.AssistantConfirmation
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AssistantConfirmationQuery builder.
func (_q *AssistantConfirmationQuery) Where(ps ...predicate.AssistantConfirmation) *AssistantConfirmationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AssistantConfirmationQuery) Limit(limit int) *AssistantConfirmationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AssistantConfirmationQuery) Offset(offset int) *AssistantConfirmationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AssistantConfirmationQuery) Unique(unique bool) *AssistantConfirmationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AssistantConfirmationQuery) Order(o ...assistantconfirmation.OrderOption) *AssistantConfirmationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first AssistantConfirmation entity from the query.
// Returns a *NotFoundError when no AssistantConfirmation was found.
func (_q *AssistantConfirmationQuery) First(ctx context.Context) (*AssistantConfirmation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{assistantconfirmation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AssistantConfirmationQuery) FirstX(ctx context.Context) *AssistantConfirmation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AssistantConfirmation ID from the query.
// Returns a *NotFoundError when no AssistantConfirmation ID was found.
func (_q *AssistantConfirmationQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{assistantconfirmation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AssistantConfirmationQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AssistantConfirmation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AssistantConfirmation entity is found.
// Returns a *NotFoundError when no AssistantConfirmation entities are found.
func (_q *AssistantConfirmationQuery) Only(ctx context.Context) (*AssistantConfirmation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{assistantconfirmation.Label}
	default:
		return nil, &NotSingularError{assistantconfirmation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AssistantConfirmationQuery) OnlyX(ctx context.Context) *AssistantConfirmation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AssistantConfirmation ID in the query.
// Returns a *NotSingularError when more than one AssistantConfirmation ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AssistantConfirmationQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{assistantconfirmation.Label}
	default:
		err = &NotSingularError{assistantconfirmation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AssistantConfirmationQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AssistantConfirmations.
func (_q *AssistantConfirmationQuery) All(ctx context.Context) ([]*AssistantConfirmation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AssistantConfirmation, *AssistantConfirmationQuery]()
	return withInterceptors[[]*AssistantConfirmation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AssistantConfirmationQuery) AllX(ctx context.Context) []*AssistantConfirmation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AssistantConfirmation IDs.
func (_q *AssistantConfirmationQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(assistantconfirmation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AssistantConfirmationQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AssistantConfirmationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AssistantConfirmationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AssistantConfirmationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AssistantConfirmationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AssistantConfirmationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AssistantConfirmationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AssistantConfirmationQuery) Clone() *AssistantConfirmationQuery {
	if _q == nil {
		return nil
	}
	return &AssistantConfirmationQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]assistantconfirmation.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.AssistantConfirmation{}, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ConfirmationKey string `json:"confirmation_key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AssistantConfirmation.Query().
//		GroupBy(assistantconfirmation.FieldConfirmationKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AssistantConfirmationQuery) GroupBy(field string, fields ...string) *AssistantConfirmationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AssistantConfirmationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = assistantconfirmation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ConfirmationKey string `json:"confirmation_key,omitempty"`
//	}
//
//	client.AssistantConfirmation.Query().
//		Select(assistantconfirmation.FieldConfirmationKey).
//		Scan(ctx, &v)
func (_q *AssistantConfirmationQuery) Select(fields ...string) *AssistantConfirmationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AssistantConfirmationSelect{AssistantConfirmationQuery: _q}
	sbuild.label = assistantconfirmation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AssistantConfirmationSelect configured with the given aggregations.
func (_q *AssistantConfirmationQuery) Aggregate(fns ...AggregateFunc) *AssistantConfirmationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AssistantConfirmationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !assistantconfirmation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AssistantConfirmationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AssistantConfirmation, error) {
	var (
		nodes = []*AssistantConfirmation{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AssistantConfirmation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AssistantConfirmation{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *AssistantConfirmationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AssistantConfirmationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(assistantconfirmation.Table, assistantconfirmation.Columns, sqlgraph.NewFieldSpec(assistantconfirmation.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assistantconfirmation.FieldID)
		for i := range fields {
			if fields[i] != assistantconfirmation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AssistantConfirmationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(assistantconfirmation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = assistantconfirmation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AssistantConfirmationGroupBy is the group-by builder for AssistantConfirmation entities.
type AssistantConfirmationGroupBy struct {
	selector
	build *AssistantConfirmationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AssistantConfirmationGroupBy) Aggregate(fns ...AggregateFunc) *AssistantConfirmationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AssistantConfirmationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssistantConfirmationQuery, *AssistantConfirmationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AssistantConfirmationGroupBy) sqlScan(ctx context.Context, root *AssistantConfirmationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AssistantConfirmationSelect is the builder for selecting fields of AssistantConfirmation entities.
type AssistantConfirmationSelect struct {
	*AssistantConfirmationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AssistantConfirmationSelect) Aggregate(fns ...AggregateFunc) *AssistantConfirmationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AssistantConfirmationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssistantConfirmationQuery, *AssistantConfirmationSelect](ctx, _s.AssistantConfirmationQuery, _s, _s.inters, v)
}

func (_s *AssistantConfirmationSelect) sqlScan(ctx context.Context, root *AssistantConfirmationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
