// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ciao1019/Petrichor/apps/api/ent/kbagentthread"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// KBAgentThreadDelete is the builder for deleting a KBAgentThread entity.
type KBAgentThreadDelete struct {
	config
	hooks    []Hook
	mutation *KBAgentThreadMutation
}

// Where appends a list predicates to the KBAgentThreadDelete builder.
func (_d *KBAgentThreadDelete) Where(ps ...predicate.KBAgentThread) *KBAgentThreadDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *KBAgentThreadDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *KBAgentThreadDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *KBAgentThreadDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(kbagentthread.Table, sqlgraph.NewFieldSpec(kbagentthread.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// KBAgentThreadDeleteOne is the builder for deleting a single KBAgentThread entity.
type KBAgentThreadDeleteOne struct {
	_d *KBAgentThreadDelete
}

// Where appends a list predicates to the KBAgentThreadDelete builder.
func (_d *KBAgentThreadDeleteOne) Where(ps ...predicate.KBAgentThread) *KBAgentThreadDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *KBAgentThreadDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{kbagentthread.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *KBAgentThreadDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
