// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Ciao1019/Petrichor/apps/api/ent/kbarticleshare"
)

// KBArticleShare is the model entity for the KBArticleShare schema.
type KBArticleShare struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ArticleID holds the value of the "article_id" field.
	ArticleID int64 `json:"article_id,omitempty"`
	// ShareCode holds the value of the "share_code" field.
	ShareCode string `json:"share_code,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash *string `json:"password_hash,omitempty"`
	// IsRepost holds the value of the "is_repost" field.
	IsRepost bool `json:"is_repost,omitempty"`
	// OriginalURL holds the value of the "original_url" field.
	OriginalURL *string `json:"original_url,omitempty"`
	// OriginalAuthorName holds the value of the "original_author_name" field.
	OriginalAuthorName *string `json:"original_author_name,omitempty"`
	// InternalURL holds the value of the "internal_url" field.
	InternalURL *string `json:"internal_url,omitempty"`
	// PinOrder holds the value of the "pin_order" field.
	PinOrder *int `json:"pin_order,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KBArticleShare) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case kbarticleshare.FieldEnabled, kbarticleshare.FieldIsRepost:
			values[i] = new(sql.NullBool)
		case kbarticleshare.FieldID, kbarticleshare.FieldUserID, kbarticleshare.FieldArticleID, kbarticleshare.FieldPinOrder:
			values[i] = new(sql.NullInt64)
		case kbarticleshare.FieldShareCode, kbarticleshare.FieldPasswordHash, kbarticleshare.FieldOriginalURL, kbarticleshare.FieldOriginalAuthorName, kbarticleshare.FieldInternalURL:
			values[i] = new(sql.NullString)
		case kbarticleshare.FieldExpiresAt, kbarticleshare.FieldRevokedAt, kbarticleshare.FieldCreatedAt, kbarticleshare.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KBArticleShare fields.
func (_m *KBArticleShare) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kbarticleshare.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case kbarticleshare.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case kbarticleshare.FieldArticleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field article_id", values[i])
			} else if value.Valid {
				_m.ArticleID = value.Int64
			}
		case kbarticleshare.FieldShareCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field share_code", values[i])
			} else if value.Valid {
				_m.ShareCode = value.String
			}
		case kbarticleshare.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case kbarticleshare.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case kbarticleshare.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = new(string)
				*_m.PasswordHash = value.String
			}
		case kbarticleshare.FieldIsRepost:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_repost", values[i])
			} else if value.Valid {
				_m.IsRepost = value.Bool
			}
		case kbarticleshare.FieldOriginalURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_url", values[i])
			} else if value.Valid {
				_m.OriginalURL = new(string)
				*_m.OriginalURL = value.String
			}
		case kbarticleshare.FieldOriginalAuthorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_author_name", values[i])
			} else if value.Valid {
				_m.OriginalAuthorName = new(string)
				*_m.OriginalAuthorName = value.String
			}
		case kbarticleshare.FieldInternalURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field internal_url", values[i])
			} else if value.Valid {
				_m.InternalURL = new(string)
				*_m.InternalURL = value.String
			}
		case kbarticleshare.FieldPinOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pin_order", values[i])
			} else if value.Valid {
				_m.PinOrder = new(int)
				*_m.PinOrder = int(value.Int64)
			}
		case kbarticleshare.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case kbarticleshare.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case kbarticleshare.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KBArticleShare.
// This includes values selected through modifiers, order, etc.
func (_m *KBArticleShare) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this KBArticleShare.
// Note that you need to call KBArticleShare.Unwrap() before calling this method if this KBArticleShare
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KBArticleShare) Update() *KBArticleShareUpdateOne {
	return NewKBArticleShareClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KBArticleShare entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KBArticleShare) Unwrap() *KBArticleShare {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KBArticleShare is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KBArticleShare) String() string {
	var builder strings.Builder
	builder.WriteString("KBArticleShare(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("article_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ArticleID))
	builder.WriteString(", ")
	builder.WriteString("share_code=")
	builder.WriteString(_m.ShareCode)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PasswordHash; v != nil {
		builder.WriteString("password_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_repost=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsRepost))
	builder.WriteString(", ")
	if v := _m.OriginalURL; v != nil {
		builder.WriteString("original_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OriginalAuthorName; v != nil {
		builder.WriteString("original_author_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.InternalURL; v != nil {
		builder.WriteString("internal_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PinOrder; v != nil {
		builder.WriteString("pin_order=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// KBArticleShares is a parsable slice of KBArticleShare.
type KBArticleShares []*KBArticleShare
