// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Ciao1019/Petrichor/apps/api/ent/kbarticleburnlink"
)

// KBArticleBurnLink is the model entity for the KBArticleBurnLink schema.
type KBArticleBurnLink struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ArticleID holds the value of the "article_id" field.
	ArticleID int64 `json:"article_id,omitempty"`
	// LinkCode holds the value of the "link_code" field.
	LinkCode string `json:"link_code,omitempty"`
	// MaxViews holds the value of the "max_views" field.
	MaxViews int `json:"max_views,omitempty"`
	// ViewCount holds the value of the "view_count" field.
	ViewCount int `json:"view_count,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash *string `json:"password_hash,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// BurnedAt holds the value of the "burned_at" field.
	BurnedAt *time.Time `json:"burned_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KBArticleBurnLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case kbarticleburnlink.FieldID, kbarticleburnlink.FieldUserID, kbarticleburnlink.FieldArticleID, kbarticleburnlink.FieldMaxViews, kbarticleburnlink.FieldViewCount:
			values[i] = new(sql.NullInt64)
		case kbarticleburnlink.FieldLinkCode, kbarticleburnlink.FieldPasswordHash, kbarticleburnlink.FieldStatus:
			values[i] = new(sql.NullString)
		case kbarticleburnlink.FieldExpiresAt, kbarticleburnlink.FieldBurnedAt, kbarticleburnlink.FieldRevokedAt, kbarticleburnlink.FieldCreatedAt, kbarticleburnlink.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KBArticleBurnLink fields.
func (_m *KBArticleBurnLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kbarticleburnlink.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case kbarticleburnlink.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case kbarticleburnlink.FieldArticleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field article_id", values[i])
			} else if value.Valid {
				_m.ArticleID = value.Int64
			}
		case kbarticleburnlink.FieldLinkCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link_code", values[i])
			} else if value.Valid {
				_m.LinkCode = value.String
			}
		case kbarticleburnlink.FieldMaxViews:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_views", values[i])
			} else if value.Valid {
				_m.MaxViews = int(value.Int64)
			}
		case kbarticleburnlink.FieldViewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field view_count", values[i])
			} else if value.Valid {
				_m.ViewCount = int(value.Int64)
			}
		case kbarticleburnlink.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = new(string)
				*_m.PasswordHash = value.String
			}
		case kbarticleburnlink.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case kbarticleburnlink.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case kbarticleburnlink.FieldBurnedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field burned_at", values[i])
			} else if value.Valid {
				_m.BurnedAt = new(time.Time)
				*_m.BurnedAt = value.Time
			}
		case kbarticleburnlink.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case kbarticleburnlink.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case kbarticleburnlink.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KBArticleBurnLink.
// This includes values selected through modifiers, order, etc.
func (_m *KBArticleBurnLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this KBArticleBurnLink.
// Note that you need to call KBArticleBurnLink.Unwrap() before calling this method if this KBArticleBurnLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KBArticleBurnLink) Update() *KBArticleBurnLinkUpdateOne {
	return NewKBArticleBurnLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KBArticleBurnLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KBArticleBurnLink) Unwrap() *KBArticleBurnLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KBArticleBurnLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KBArticleBurnLink) String() string {
	var builder strings.Builder
	builder.WriteString("KBArticleBurnLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("article_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ArticleID))
	builder.WriteString(", ")
	builder.WriteString("link_code=")
	builder.WriteString(_m.LinkCode)
	builder.WriteString(", ")
	builder.WriteString("max_views=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxViews))
	builder.WriteString(", ")
	builder.WriteString("view_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ViewCount))
	builder.WriteString(", ")
	if v := _m.PasswordHash; v != nil {
		builder.WriteString("password_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.BurnedAt; v != nil {
		builder.WriteString("burned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// KBArticleBurnLinks is a parsable slice of KBArticleBurnLink.
type KBArticleBurnLinks []*KBArticleBurnLink
