// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ciao1019/Petrichor/apps/api/ent/kbdocumentchunkquestion"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// KBDocumentChunkQuestionDelete is the builder for deleting a KBDocumentChunkQuestion entity.
type KBDocumentChunkQuestionDelete struct {
	config
	hooks    []Hook
	mutation *KBDocumentChunkQuestionMutation
}

// Where appends a list predicates to the KBDocumentChunkQuestionDelete builder.
func (_d *KBDocumentChunkQuestionDelete) Where(ps ...predicate.KBDocumentChunkQuestion) *KBDocumentChunkQuestionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *KBDocumentChunkQuestionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *KBDocumentChunkQuestionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *KBDocumentChunkQuestionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(kbdocumentchunkquestion.Table, sqlgraph.NewFieldSpec(kbdocumentchunkquestion.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// KBDocumentChunkQuestionDeleteOne is the builder for deleting a single KBDocumentChunkQuestion entity.
type KBDocumentChunkQuestionDeleteOne struct {
	_d *KBDocumentChunkQuestionDelete
}

// Where appends a list predicates to the KBDocumentChunkQuestionDelete builder.
func (_d *KBDocumentChunkQuestionDeleteOne) Where(ps ...predicate.KBDocumentChunkQuestion) *KBDocumentChunkQuestionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *KBDocumentChunkQuestionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{kbdocumentchunkquestion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *KBDocumentChunkQuestionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
