// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ciao1019/Petrichor/apps/api/ent/kbdocumentspan"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// KBDocumentSpanUpdate is the builder for updating KBDocumentSpan entities.
type KBDocumentSpanUpdate struct {
	config
	hooks    []Hook
	mutation *KBDocumentSpanMutation
}

// Where appends a list predicates to the KBDocumentSpanUpdate builder.
func (_u *KBDocumentSpanUpdate) Where(ps ...predicate.KBDocumentSpan) *KBDocumentSpanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *KBDocumentSpanUpdate) SetUserID(v int64) *KBDocumentSpanUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableUserID(v *int64) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *KBDocumentSpanUpdate) AddUserID(v int64) *KBDocumentSpanUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *KBDocumentSpanUpdate) SetDocumentID(v int64) *KBDocumentSpanUpdate {
	_u.mutation.ResetDocumentID()
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableDocumentID(v *int64) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// AddDocumentID adds value to the "document_id" field.
func (_u *KBDocumentSpanUpdate) AddDocumentID(v int64) *KBDocumentSpanUpdate {
	_u.mutation.AddDocumentID(v)
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *KBDocumentSpanUpdate) SetAttempt(v int) *KBDocumentSpanUpdate {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableAttempt(v *int) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *KBDocumentSpanUpdate) AddAttempt(v int) *KBDocumentSpanUpdate {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetSpanID sets the "span_id" field.
func (_u *KBDocumentSpanUpdate) SetSpanID(v string) *KBDocumentSpanUpdate {
	_u.mutation.SetSpanID(v)
	return _u
}

// SetNillableSpanID sets the "span_id" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableSpanID(v *string) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetSpanID(*v)
	}
	return _u
}

// SetParentSpanID sets the "parent_span_id" field.
func (_u *KBDocumentSpanUpdate) SetParentSpanID(v string) *KBDocumentSpanUpdate {
	_u.mutation.SetParentSpanID(v)
	return _u
}

// SetNillableParentSpanID sets the "parent_span_id" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableParentSpanID(v *string) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetParentSpanID(*v)
	}
	return _u
}

// ClearParentSpanID clears the value of the "parent_span_id" field.
func (_u *KBDocumentSpanUpdate) ClearParentSpanID() *KBDocumentSpanUpdate {
	_u.mutation.ClearParentSpanID()
	return _u
}

// SetName sets the "name" field.
func (_u *KBDocumentSpanUpdate) SetName(v string) *KBDocumentSpanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableName(v *string) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *KBDocumentSpanUpdate) SetKind(v string) *KBDocumentSpanUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableKind(v *string) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *KBDocumentSpanUpdate) SetStatus(v string) *KBDocumentSpanUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableStatus(v *string) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInput sets the "input" field.
func (_u *KBDocumentSpanUpdate) SetInput(v string) *KBDocumentSpanUpdate {
	_u.mutation.SetInput(v)
	return _u
}

// SetNillableInput sets the "input" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableInput(v *string) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetInput(*v)
	}
	return _u
}

// ClearInput clears the value of the "input" field.
func (_u *KBDocumentSpanUpdate) ClearInput() *KBDocumentSpanUpdate {
	_u.mutation.ClearInput()
	return _u
}

// SetOutput sets the "output" field.
func (_u *KBDocumentSpanUpdate) SetOutput(v string) *KBDocumentSpanUpdate {
	_u.mutation.SetOutput(v)
	return _u
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableOutput(v *string) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetOutput(*v)
	}
	return _u
}

// ClearOutput clears the value of the "output" field.
func (_u *KBDocumentSpanUpdate) ClearOutput() *KBDocumentSpanUpdate {
	_u.mutation.ClearOutput()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *KBDocumentSpanUpdate) SetErrorCode(v string) *KBDocumentSpanUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableErrorCode(v *string) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *KBDocumentSpanUpdate) ClearErrorCode() *KBDocumentSpanUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *KBDocumentSpanUpdate) SetErrorMessage(v string) *KBDocumentSpanUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableErrorMessage(v *string) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *KBDocumentSpanUpdate) ClearErrorMessage() *KBDocumentSpanUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *KBDocumentSpanUpdate) SetStartedAt(v time.Time) *KBDocumentSpanUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableStartedAt(v *time.Time) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *KBDocumentSpanUpdate) ClearStartedAt() *KBDocumentSpanUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *KBDocumentSpanUpdate) SetFinishedAt(v time.Time) *KBDocumentSpanUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableFinishedAt(v *time.Time) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *KBDocumentSpanUpdate) ClearFinishedAt() *KBDocumentSpanUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *KBDocumentSpanUpdate) SetDurationMs(v int64) *KBDocumentSpanUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *KBDocumentSpanUpdate) SetNillableDurationMs(v *int64) *KBDocumentSpanUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *KBDocumentSpanUpdate) AddDurationMs(v int64) *KBDocumentSpanUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KBDocumentSpanUpdate) SetUpdatedAt(v time.Time) *KBDocumentSpanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the KBDocumentSpanMutation object of the builder.
func (_u *KBDocumentSpanUpdate) Mutation() *KBDocumentSpanMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KBDocumentSpanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KBDocumentSpanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KBDocumentSpanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KBDocumentSpanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KBDocumentSpanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := kbdocumentspan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KBDocumentSpanUpdate) check() error {
	if v, ok := _u.mutation.SpanID(); ok {
		if err := kbdocumentspan.SpanIDValidator(v); err != nil {
			return &ValidationError{Name: "span_id", err: fmt.Errorf(`ent: validator failed for field "KBDocumentSpan.span_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := kbdocumentspan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "KBDocumentSpan.name": %w`, err)}
		}
	}
	return nil
}

func (_u *KBDocumentSpanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kbdocumentspan.Table, kbdocumentspan.Columns, sqlgraph.NewFieldSpec(kbdocumentspan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(kbdocumentspan.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(kbdocumentspan.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DocumentID(); ok {
		_spec.SetField(kbdocumentspan.FieldDocumentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDocumentID(); ok {
		_spec.AddField(kbdocumentspan.FieldDocumentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(kbdocumentspan.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(kbdocumentspan.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SpanID(); ok {
		_spec.SetField(kbdocumentspan.FieldSpanID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentSpanID(); ok {
		_spec.SetField(kbdocumentspan.FieldParentSpanID, field.TypeString, value)
	}
	if _u.mutation.ParentSpanIDCleared() {
		_spec.ClearField(kbdocumentspan.FieldParentSpanID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(kbdocumentspan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(kbdocumentspan.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(kbdocumentspan.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(kbdocumentspan.FieldInput, field.TypeString, value)
	}
	if _u.mutation.InputCleared() {
		_spec.ClearField(kbdocumentspan.FieldInput, field.TypeString)
	}
	if value, ok := _u.mutation.Output(); ok {
		_spec.SetField(kbdocumentspan.FieldOutput, field.TypeString, value)
	}
	if _u.mutation.OutputCleared() {
		_spec.ClearField(kbdocumentspan.FieldOutput, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(kbdocumentspan.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(kbdocumentspan.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(kbdocumentspan.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(kbdocumentspan.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(kbdocumentspan.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(kbdocumentspan.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(kbdocumentspan.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(kbdocumentspan.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(kbdocumentspan.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(kbdocumentspan.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kbdocumentspan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kbdocumentspan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KBDocumentSpanUpdateOne is the builder for updating a single KBDocumentSpan entity.
type KBDocumentSpanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KBDocumentSpanMutation
}

// SetUserID sets the "user_id" field.
func (_u *KBDocumentSpanUpdateOne) SetUserID(v int64) *KBDocumentSpanUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableUserID(v *int64) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *KBDocumentSpanUpdateOne) AddUserID(v int64) *KBDocumentSpanUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *KBDocumentSpanUpdateOne) SetDocumentID(v int64) *KBDocumentSpanUpdateOne {
	_u.mutation.ResetDocumentID()
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableDocumentID(v *int64) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// AddDocumentID adds value to the "document_id" field.
func (_u *KBDocumentSpanUpdateOne) AddDocumentID(v int64) *KBDocumentSpanUpdateOne {
	_u.mutation.AddDocumentID(v)
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *KBDocumentSpanUpdateOne) SetAttempt(v int) *KBDocumentSpanUpdateOne {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableAttempt(v *int) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *KBDocumentSpanUpdateOne) AddAttempt(v int) *KBDocumentSpanUpdateOne {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetSpanID sets the "span_id" field.
func (_u *KBDocumentSpanUpdateOne) SetSpanID(v string) *KBDocumentSpanUpdateOne {
	_u.mutation.SetSpanID(v)
	return _u
}

// SetNillableSpanID sets the "span_id" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableSpanID(v *string) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetSpanID(*v)
	}
	return _u
}

// SetParentSpanID sets the "parent_span_id" field.
func (_u *KBDocumentSpanUpdateOne) SetParentSpanID(v string) *KBDocumentSpanUpdateOne {
	_u.mutation.SetParentSpanID(v)
	return _u
}

// SetNillableParentSpanID sets the "parent_span_id" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableParentSpanID(v *string) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetParentSpanID(*v)
	}
	return _u
}

// ClearParentSpanID clears the value of the "parent_span_id" field.
func (_u *KBDocumentSpanUpdateOne) ClearParentSpanID() *KBDocumentSpanUpdateOne {
	_u.mutation.ClearParentSpanID()
	return _u
}

// SetName sets the "name" field.
func (_u *KBDocumentSpanUpdateOne) SetName(v string) *KBDocumentSpanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableName(v *string) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *KBDocumentSpanUpdateOne) SetKind(v string) *KBDocumentSpanUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableKind(v *string) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *KBDocumentSpanUpdateOne) SetStatus(v string) *KBDocumentSpanUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableStatus(v *string) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInput sets the "input" field.
func (_u *KBDocumentSpanUpdateOne) SetInput(v string) *KBDocumentSpanUpdateOne {
	_u.mutation.SetInput(v)
	return _u
}

// SetNillableInput sets the "input" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableInput(v *string) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetInput(*v)
	}
	return _u
}

// ClearInput clears the value of the "input" field.
func (_u *KBDocumentSpanUpdateOne) ClearInput() *KBDocumentSpanUpdateOne {
	_u.mutation.ClearInput()
	return _u
}

// SetOutput sets the "output" field.
func (_u *KBDocumentSpanUpdateOne) SetOutput(v string) *KBDocumentSpanUpdateOne {
	_u.mutation.SetOutput(v)
	return _u
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableOutput(v *string) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetOutput(*v)
	}
	return _u
}

// ClearOutput clears the value of the "output" field.
func (_u *KBDocumentSpanUpdateOne) ClearOutput() *KBDocumentSpanUpdateOne {
	_u.mutation.ClearOutput()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *KBDocumentSpanUpdateOne) SetErrorCode(v string) *KBDocumentSpanUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableErrorCode(v *string) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *KBDocumentSpanUpdateOne) ClearErrorCode() *KBDocumentSpanUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *KBDocumentSpanUpdateOne) SetErrorMessage(v string) *KBDocumentSpanUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableErrorMessage(v *string) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *KBDocumentSpanUpdateOne) ClearErrorMessage() *KBDocumentSpanUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *KBDocumentSpanUpdateOne) SetStartedAt(v time.Time) *KBDocumentSpanUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableStartedAt(v *time.Time) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *KBDocumentSpanUpdateOne) ClearStartedAt() *KBDocumentSpanUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *KBDocumentSpanUpdateOne) SetFinishedAt(v time.Time) *KBDocumentSpanUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableFinishedAt(v *time.Time) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *KBDocumentSpanUpdateOne) ClearFinishedAt() *KBDocumentSpanUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *KBDocumentSpanUpdateOne) SetDurationMs(v int64) *KBDocumentSpanUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *KBDocumentSpanUpdateOne) SetNillableDurationMs(v *int64) *KBDocumentSpanUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *KBDocumentSpanUpdateOne) AddDurationMs(v int64) *KBDocumentSpanUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KBDocumentSpanUpdateOne) SetUpdatedAt(v time.Time) *KBDocumentSpanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the KBDocumentSpanMutation object of the builder.
func (_u *KBDocumentSpanUpdateOne) Mutation() *KBDocumentSpanMutation {
	return _u.mutation
}

// Where appends a list predicates to the KBDocumentSpanUpdate builder.
func (_u *KBDocumentSpanUpdateOne) Where(ps ...predicate.KBDocumentSpan) *KBDocumentSpanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KBDocumentSpanUpdateOne) Select(field string, fields ...string) *KBDocumentSpanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KBDocumentSpan entity.
func (_u *KBDocumentSpanUpdateOne) Save(ctx context.Context) (*KBDocumentSpan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KBDocumentSpanUpdateOne) SaveX(ctx context.Context) *KBDocumentSpan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KBDocumentSpanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KBDocumentSpanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KBDocumentSpanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := kbdocumentspan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KBDocumentSpanUpdateOne) check() error {
	if v, ok := _u.mutation.SpanID(); ok {
		if err := kbdocumentspan.SpanIDValidator(v); err != nil {
			return &ValidationError{Name: "span_id", err: fmt.Errorf(`ent: validator failed for field "KBDocumentSpan.span_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := kbdocumentspan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "KBDocumentSpan.name": %w`, err)}
		}
	}
	return nil
}

func (_u *KBDocumentSpanUpdateOne) sqlSave(ctx context.Context) (_node *KBDocumentSpan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kbdocumentspan.Table, kbdocumentspan.Columns, sqlgraph.NewFieldSpec(kbdocumentspan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KBDocumentSpan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, kbdocumentspan.FieldID)
		for _, f := range fields {
			if !kbdocumentspan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != kbdocumentspan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(kbdocumentspan.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(kbdocumentspan.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DocumentID(); ok {
		_spec.SetField(kbdocumentspan.FieldDocumentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDocumentID(); ok {
		_spec.AddField(kbdocumentspan.FieldDocumentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(kbdocumentspan.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(kbdocumentspan.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SpanID(); ok {
		_spec.SetField(kbdocumentspan.FieldSpanID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentSpanID(); ok {
		_spec.SetField(kbdocumentspan.FieldParentSpanID, field.TypeString, value)
	}
	if _u.mutation.ParentSpanIDCleared() {
		_spec.ClearField(kbdocumentspan.FieldParentSpanID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(kbdocumentspan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(kbdocumentspan.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(kbdocumentspan.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(kbdocumentspan.FieldInput, field.TypeString, value)
	}
	if _u.mutation.InputCleared() {
		_spec.ClearField(kbdocumentspan.FieldInput, field.TypeString)
	}
	if value, ok := _u.mutation.Output(); ok {
		_spec.SetField(kbdocumentspan.FieldOutput, field.TypeString, value)
	}
	if _u.mutation.OutputCleared() {
		_spec.ClearField(kbdocumentspan.FieldOutput, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(kbdocumentspan.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(kbdocumentspan.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(kbdocumentspan.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(kbdocumentspan.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(kbdocumentspan.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(kbdocumentspan.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(kbdocumentspan.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(kbdocumentspan.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(kbdocumentspan.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(kbdocumentspan.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kbdocumentspan.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &KBDocumentSpan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kbdocumentspan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
