// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Ciao1019/Petrichor/apps/api/ent/kbdocumentchunk"
)

// KBDocumentChunk is the model entity for the KBDocumentChunk schema.
type KBDocumentChunk struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// KnowledgeBaseID holds the value of the "knowledge_base_id" field.
	KnowledgeBaseID int64 `json:"knowledge_base_id,omitempty"`
	// DocumentID holds the value of the "document_id" field.
	DocumentID int64 `json:"document_id,omitempty"`
	// ChunkIndex holds the value of the "chunk_index" field.
	ChunkIndex int `json:"chunk_index,omitempty"`
	// Locator holds the value of the "locator" field.
	Locator *string `json:"locator,omitempty"`
	// Page holds the value of the "page" field.
	Page *int `json:"page,omitempty"`
	// ContextHeader holds the value of the "context_header" field.
	ContextHeader *string `json:"context_header,omitempty"`
	// StartOffset holds the value of the "start_offset" field.
	StartOffset *int `json:"start_offset,omitempty"`
	// EndOffset holds the value of the "end_offset" field.
	EndOffset *int `json:"end_offset,omitempty"`
	// ChunkType holds the value of the "chunk_type" field.
	ChunkType string `json:"chunk_type,omitempty"`
	// ParentChunkIndex holds the value of the "parent_chunk_index" field.
	ParentChunkIndex *int `json:"parent_chunk_index,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// CharCount holds the value of the "char_count" field.
	CharCount int `json:"char_count,omitempty"`
	// TokenEstimate holds the value of the "token_estimate" field.
	TokenEstimate int `json:"token_estimate,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KBDocumentChunk) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case kbdocumentchunk.FieldID, kbdocumentchunk.FieldUserID, kbdocumentchunk.FieldKnowledgeBaseID, kbdocumentchunk.FieldDocumentID, kbdocumentchunk.FieldChunkIndex, kbdocumentchunk.FieldPage, kbdocumentchunk.FieldStartOffset, kbdocumentchunk.FieldEndOffset, kbdocumentchunk.FieldParentChunkIndex, kbdocumentchunk.FieldCharCount, kbdocumentchunk.FieldTokenEstimate:
			values[i] = new(sql.NullInt64)
		case kbdocumentchunk.FieldLocator, kbdocumentchunk.FieldContextHeader, kbdocumentchunk.FieldChunkType, kbdocumentchunk.FieldText:
			values[i] = new(sql.NullString)
		case kbdocumentchunk.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KBDocumentChunk fields.
func (_m *KBDocumentChunk) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kbdocumentchunk.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case kbdocumentchunk.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case kbdocumentchunk.FieldKnowledgeBaseID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field knowledge_base_id", values[i])
			} else if value.Valid {
				_m.KnowledgeBaseID = value.Int64
			}
		case kbdocumentchunk.FieldDocumentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field document_id", values[i])
			} else if value.Valid {
				_m.DocumentID = value.Int64
			}
		case kbdocumentchunk.FieldChunkIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chunk_index", values[i])
			} else if value.Valid {
				_m.ChunkIndex = int(value.Int64)
			}
		case kbdocumentchunk.FieldLocator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locator", values[i])
			} else if value.Valid {
				_m.Locator = new(string)
				*_m.Locator = value.String
			}
		case kbdocumentchunk.FieldPage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field page", values[i])
			} else if value.Valid {
				_m.Page = new(int)
				*_m.Page = int(value.Int64)
			}
		case kbdocumentchunk.FieldContextHeader:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context_header", values[i])
			} else if value.Valid {
				_m.ContextHeader = new(string)
				*_m.ContextHeader = value.String
			}
		case kbdocumentchunk.FieldStartOffset:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_offset", values[i])
			} else if value.Valid {
				_m.StartOffset = new(int)
				*_m.StartOffset = int(value.Int64)
			}
		case kbdocumentchunk.FieldEndOffset:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field end_offset", values[i])
			} else if value.Valid {
				_m.EndOffset = new(int)
				*_m.EndOffset = int(value.Int64)
			}
		case kbdocumentchunk.FieldChunkType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chunk_type", values[i])
			} else if value.Valid {
				_m.ChunkType = value.String
			}
		case kbdocumentchunk.FieldParentChunkIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_chunk_index", values[i])
			} else if value.Valid {
				_m.ParentChunkIndex = new(int)
				*_m.ParentChunkIndex = int(value.Int64)
			}
		case kbdocumentchunk.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case kbdocumentchunk.FieldCharCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field char_count", values[i])
			} else if value.Valid {
				_m.CharCount = int(value.Int64)
			}
		case kbdocumentchunk.FieldTokenEstimate:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_estimate", values[i])
			} else if value.Valid {
				_m.TokenEstimate = int(value.Int64)
			}
		case kbdocumentchunk.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KBDocumentChunk.
// This includes values selected through modifiers, order, etc.
func (_m *KBDocumentChunk) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this KBDocumentChunk.
// Note that you need to call KBDocumentChunk.Unwrap() before calling this method if this KBDocumentChunk
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KBDocumentChunk) Update() *KBDocumentChunkUpdateOne {
	return NewKBDocumentChunkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KBDocumentChunk entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KBDocumentChunk) Unwrap() *KBDocumentChunk {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KBDocumentChunk is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KBDocumentChunk) String() string {
	var builder strings.Builder
	builder.WriteString("KBDocumentChunk(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("knowledge_base_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.KnowledgeBaseID))
	builder.WriteString(", ")
	builder.WriteString("document_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DocumentID))
	builder.WriteString(", ")
	builder.WriteString("chunk_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChunkIndex))
	builder.WriteString(", ")
	if v := _m.Locator; v != nil {
		builder.WriteString("locator=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Page; v != nil {
		builder.WriteString("page=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ContextHeader; v != nil {
		builder.WriteString("context_header=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.StartOffset; v != nil {
		builder.WriteString("start_offset=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.EndOffset; v != nil {
		builder.WriteString("end_offset=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("chunk_type=")
	builder.WriteString(_m.ChunkType)
	builder.WriteString(", ")
	if v := _m.ParentChunkIndex; v != nil {
		builder.WriteString("parent_chunk_index=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("char_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CharCount))
	builder.WriteString(", ")
	builder.WriteString("token_estimate=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenEstimate))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// KBDocumentChunks is a parsable slice of KBDocumentChunk.
type KBDocumentChunks []*KBDocumentChunk
