// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ciao1019/Petrichor/apps/api/ent/kbimportjob"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// KBImportJobUpdate is the builder for updating KBImportJob entities.
type KBImportJobUpdate struct {
	config
	hooks    []Hook
	mutation *KBImportJobMutation
}

// Where appends a list predicates to the KBImportJobUpdate builder.
func (_u *KBImportJobUpdate) Where(ps ...predicate.KBImportJob) *KBImportJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *KBImportJobUpdate) SetUserID(v int64) *KBImportJobUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableUserID(v *int64) *KBImportJobUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *KBImportJobUpdate) AddUserID(v int64) *KBImportJobUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKnowledgeBaseID sets the "knowledge_base_id" field.
func (_u *KBImportJobUpdate) SetKnowledgeBaseID(v int64) *KBImportJobUpdate {
	_u.mutation.ResetKnowledgeBaseID()
	_u.mutation.SetKnowledgeBaseID(v)
	return _u
}

// SetNillableKnowledgeBaseID sets the "knowledge_base_id" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableKnowledgeBaseID(v *int64) *KBImportJobUpdate {
	if v != nil {
		_u.SetKnowledgeBaseID(*v)
	}
	return _u
}

// AddKnowledgeBaseID adds value to the "knowledge_base_id" field.
func (_u *KBImportJobUpdate) AddKnowledgeBaseID(v int64) *KBImportJobUpdate {
	_u.mutation.AddKnowledgeBaseID(v)
	return _u
}

// SetParentNodeID sets the "parent_node_id" field.
func (_u *KBImportJobUpdate) SetParentNodeID(v int64) *KBImportJobUpdate {
	_u.mutation.ResetParentNodeID()
	_u.mutation.SetParentNodeID(v)
	return _u
}

// SetNillableParentNodeID sets the "parent_node_id" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableParentNodeID(v *int64) *KBImportJobUpdate {
	if v != nil {
		_u.SetParentNodeID(*v)
	}
	return _u
}

// AddParentNodeID adds value to the "parent_node_id" field.
func (_u *KBImportJobUpdate) AddParentNodeID(v int64) *KBImportJobUpdate {
	_u.mutation.AddParentNodeID(v)
	return _u
}

// ClearParentNodeID clears the value of the "parent_node_id" field.
func (_u *KBImportJobUpdate) ClearParentNodeID() *KBImportJobUpdate {
	_u.mutation.ClearParentNodeID()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *KBImportJobUpdate) SetSourceType(v string) *KBImportJobUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableSourceType(v *string) *KBImportJobUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *KBImportJobUpdate) SetFileName(v string) *KBImportJobUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableFileName(v *string) *KBImportJobUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetSourceKey sets the "source_key" field.
func (_u *KBImportJobUpdate) SetSourceKey(v string) *KBImportJobUpdate {
	_u.mutation.SetSourceKey(v)
	return _u
}

// SetNillableSourceKey sets the "source_key" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableSourceKey(v *string) *KBImportJobUpdate {
	if v != nil {
		_u.SetSourceKey(*v)
	}
	return _u
}

// ClearSourceKey clears the value of the "source_key" field.
func (_u *KBImportJobUpdate) ClearSourceKey() *KBImportJobUpdate {
	_u.mutation.ClearSourceKey()
	return _u
}

// SetTitle sets the "title" field.
func (_u *KBImportJobUpdate) SetTitle(v string) *KBImportJobUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableTitle(v *string) *KBImportJobUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTotalPages sets the "total_pages" field.
func (_u *KBImportJobUpdate) SetTotalPages(v int) *KBImportJobUpdate {
	_u.mutation.ResetTotalPages()
	_u.mutation.SetTotalPages(v)
	return _u
}

// SetNillableTotalPages sets the "total_pages" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableTotalPages(v *int) *KBImportJobUpdate {
	if v != nil {
		_u.SetTotalPages(*v)
	}
	return _u
}

// AddTotalPages adds value to the "total_pages" field.
func (_u *KBImportJobUpdate) AddTotalPages(v int) *KBImportJobUpdate {
	_u.mutation.AddTotalPages(v)
	return _u
}

// SetProcessedPages sets the "processed_pages" field.
func (_u *KBImportJobUpdate) SetProcessedPages(v int) *KBImportJobUpdate {
	_u.mutation.ResetProcessedPages()
	_u.mutation.SetProcessedPages(v)
	return _u
}

// SetNillableProcessedPages sets the "processed_pages" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableProcessedPages(v *int) *KBImportJobUpdate {
	if v != nil {
		_u.SetProcessedPages(*v)
	}
	return _u
}

// AddProcessedPages adds value to the "processed_pages" field.
func (_u *KBImportJobUpdate) AddProcessedPages(v int) *KBImportJobUpdate {
	_u.mutation.AddProcessedPages(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *KBImportJobUpdate) SetStatus(v string) *KBImportJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableStatus(v *string) *KBImportJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetModelConfigID sets the "model_config_id" field.
func (_u *KBImportJobUpdate) SetModelConfigID(v int64) *KBImportJobUpdate {
	_u.mutation.ResetModelConfigID()
	_u.mutation.SetModelConfigID(v)
	return _u
}

// SetNillableModelConfigID sets the "model_config_id" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableModelConfigID(v *int64) *KBImportJobUpdate {
	if v != nil {
		_u.SetModelConfigID(*v)
	}
	return _u
}

// AddModelConfigID adds value to the "model_config_id" field.
func (_u *KBImportJobUpdate) AddModelConfigID(v int64) *KBImportJobUpdate {
	_u.mutation.AddModelConfigID(v)
	return _u
}

// ClearModelConfigID clears the value of the "model_config_id" field.
func (_u *KBImportJobUpdate) ClearModelConfigID() *KBImportJobUpdate {
	_u.mutation.ClearModelConfigID()
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *KBImportJobUpdate) SetArticleID(v int64) *KBImportJobUpdate {
	_u.mutation.ResetArticleID()
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableArticleID(v *int64) *KBImportJobUpdate {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// AddArticleID adds value to the "article_id" field.
func (_u *KBImportJobUpdate) AddArticleID(v int64) *KBImportJobUpdate {
	_u.mutation.AddArticleID(v)
	return _u
}

// ClearArticleID clears the value of the "article_id" field.
func (_u *KBImportJobUpdate) ClearArticleID() *KBImportJobUpdate {
	_u.mutation.ClearArticleID()
	return _u
}

// SetError sets the "error" field.
func (_u *KBImportJobUpdate) SetError(v string) *KBImportJobUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *KBImportJobUpdate) SetNillableError(v *string) *KBImportJobUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *KBImportJobUpdate) ClearError() *KBImportJobUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KBImportJobUpdate) SetUpdatedAt(v time.Time) *KBImportJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the KBImportJobMutation object of the builder.
func (_u *KBImportJobUpdate) Mutation() *KBImportJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KBImportJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KBImportJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KBImportJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KBImportJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KBImportJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := kbimportjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KBImportJobUpdate) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := kbimportjob.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "KBImportJob.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := kbimportjob.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "KBImportJob.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := kbimportjob.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "KBImportJob.title": %w`, err)}
		}
	}
	return nil
}

func (_u *KBImportJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kbimportjob.Table, kbimportjob.Columns, sqlgraph.NewFieldSpec(kbimportjob.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(kbimportjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(kbimportjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.KnowledgeBaseID(); ok {
		_spec.SetField(kbimportjob.FieldKnowledgeBaseID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedKnowledgeBaseID(); ok {
		_spec.AddField(kbimportjob.FieldKnowledgeBaseID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParentNodeID(); ok {
		_spec.SetField(kbimportjob.FieldParentNodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentNodeID(); ok {
		_spec.AddField(kbimportjob.FieldParentNodeID, field.TypeInt64, value)
	}
	if _u.mutation.ParentNodeIDCleared() {
		_spec.ClearField(kbimportjob.FieldParentNodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(kbimportjob.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(kbimportjob.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceKey(); ok {
		_spec.SetField(kbimportjob.FieldSourceKey, field.TypeString, value)
	}
	if _u.mutation.SourceKeyCleared() {
		_spec.ClearField(kbimportjob.FieldSourceKey, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(kbimportjob.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalPages(); ok {
		_spec.SetField(kbimportjob.FieldTotalPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalPages(); ok {
		_spec.AddField(kbimportjob.FieldTotalPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProcessedPages(); ok {
		_spec.SetField(kbimportjob.FieldProcessedPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProcessedPages(); ok {
		_spec.AddField(kbimportjob.FieldProcessedPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(kbimportjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelConfigID(); ok {
		_spec.SetField(kbimportjob.FieldModelConfigID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedModelConfigID(); ok {
		_spec.AddField(kbimportjob.FieldModelConfigID, field.TypeInt64, value)
	}
	if _u.mutation.ModelConfigIDCleared() {
		_spec.ClearField(kbimportjob.FieldModelConfigID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ArticleID(); ok {
		_spec.SetField(kbimportjob.FieldArticleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedArticleID(); ok {
		_spec.AddField(kbimportjob.FieldArticleID, field.TypeInt64, value)
	}
	if _u.mutation.ArticleIDCleared() {
		_spec.ClearField(kbimportjob.FieldArticleID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(kbimportjob.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(kbimportjob.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kbimportjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kbimportjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KBImportJobUpdateOne is the builder for updating a single KBImportJob entity.
type KBImportJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KBImportJobMutation
}

// SetUserID sets the "user_id" field.
func (_u *KBImportJobUpdateOne) SetUserID(v int64) *KBImportJobUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableUserID(v *int64) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *KBImportJobUpdateOne) AddUserID(v int64) *KBImportJobUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKnowledgeBaseID sets the "knowledge_base_id" field.
func (_u *KBImportJobUpdateOne) SetKnowledgeBaseID(v int64) *KBImportJobUpdateOne {
	_u.mutation.ResetKnowledgeBaseID()
	_u.mutation.SetKnowledgeBaseID(v)
	return _u
}

// SetNillableKnowledgeBaseID sets the "knowledge_base_id" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableKnowledgeBaseID(v *int64) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetKnowledgeBaseID(*v)
	}
	return _u
}

// AddKnowledgeBaseID adds value to the "knowledge_base_id" field.
func (_u *KBImportJobUpdateOne) AddKnowledgeBaseID(v int64) *KBImportJobUpdateOne {
	_u.mutation.AddKnowledgeBaseID(v)
	return _u
}

// SetParentNodeID sets the "parent_node_id" field.
func (_u *KBImportJobUpdateOne) SetParentNodeID(v int64) *KBImportJobUpdateOne {
	_u.mutation.ResetParentNodeID()
	_u.mutation.SetParentNodeID(v)
	return _u
}

// SetNillableParentNodeID sets the "parent_node_id" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableParentNodeID(v *int64) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetParentNodeID(*v)
	}
	return _u
}

// AddParentNodeID adds value to the "parent_node_id" field.
func (_u *KBImportJobUpdateOne) AddParentNodeID(v int64) *KBImportJobUpdateOne {
	_u.mutation.AddParentNodeID(v)
	return _u
}

// ClearParentNodeID clears the value of the "parent_node_id" field.
func (_u *KBImportJobUpdateOne) ClearParentNodeID() *KBImportJobUpdateOne {
	_u.mutation.ClearParentNodeID()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *KBImportJobUpdateOne) SetSourceType(v string) *KBImportJobUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableSourceType(v *string) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *KBImportJobUpdateOne) SetFileName(v string) *KBImportJobUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableFileName(v *string) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetSourceKey sets the "source_key" field.
func (_u *KBImportJobUpdateOne) SetSourceKey(v string) *KBImportJobUpdateOne {
	_u.mutation.SetSourceKey(v)
	return _u
}

// SetNillableSourceKey sets the "source_key" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableSourceKey(v *string) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetSourceKey(*v)
	}
	return _u
}

// ClearSourceKey clears the value of the "source_key" field.
func (_u *KBImportJobUpdateOne) ClearSourceKey() *KBImportJobUpdateOne {
	_u.mutation.ClearSourceKey()
	return _u
}

// SetTitle sets the "title" field.
func (_u *KBImportJobUpdateOne) SetTitle(v string) *KBImportJobUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableTitle(v *string) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTotalPages sets the "total_pages" field.
func (_u *KBImportJobUpdateOne) SetTotalPages(v int) *KBImportJobUpdateOne {
	_u.mutation.ResetTotalPages()
	_u.mutation.SetTotalPages(v)
	return _u
}

// SetNillableTotalPages sets the "total_pages" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableTotalPages(v *int) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetTotalPages(*v)
	}
	return _u
}

// AddTotalPages adds value to the "total_pages" field.
func (_u *KBImportJobUpdateOne) AddTotalPages(v int) *KBImportJobUpdateOne {
	_u.mutation.AddTotalPages(v)
	return _u
}

// SetProcessedPages sets the "processed_pages" field.
func (_u *KBImportJobUpdateOne) SetProcessedPages(v int) *KBImportJobUpdateOne {
	_u.mutation.ResetProcessedPages()
	_u.mutation.SetProcessedPages(v)
	return _u
}

// SetNillableProcessedPages sets the "processed_pages" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableProcessedPages(v *int) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetProcessedPages(*v)
	}
	return _u
}

// AddProcessedPages adds value to the "processed_pages" field.
func (_u *KBImportJobUpdateOne) AddProcessedPages(v int) *KBImportJobUpdateOne {
	_u.mutation.AddProcessedPages(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *KBImportJobUpdateOne) SetStatus(v string) *KBImportJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableStatus(v *string) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetModelConfigID sets the "model_config_id" field.
func (_u *KBImportJobUpdateOne) SetModelConfigID(v int64) *KBImportJobUpdateOne {
	_u.mutation.ResetModelConfigID()
	_u.mutation.SetModelConfigID(v)
	return _u
}

// SetNillableModelConfigID sets the "model_config_id" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableModelConfigID(v *int64) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetModelConfigID(*v)
	}
	return _u
}

// AddModelConfigID adds value to the "model_config_id" field.
func (_u *KBImportJobUpdateOne) AddModelConfigID(v int64) *KBImportJobUpdateOne {
	_u.mutation.AddModelConfigID(v)
	return _u
}

// ClearModelConfigID clears the value of the "model_config_id" field.
func (_u *KBImportJobUpdateOne) ClearModelConfigID() *KBImportJobUpdateOne {
	_u.mutation.ClearModelConfigID()
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *KBImportJobUpdateOne) SetArticleID(v int64) *KBImportJobUpdateOne {
	_u.mutation.ResetArticleID()
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableArticleID(v *int64) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// AddArticleID adds value to the "article_id" field.
func (_u *KBImportJobUpdateOne) AddArticleID(v int64) *KBImportJobUpdateOne {
	_u.mutation.AddArticleID(v)
	return _u
}

// ClearArticleID clears the value of the "article_id" field.
func (_u *KBImportJobUpdateOne) ClearArticleID() *KBImportJobUpdateOne {
	_u.mutation.ClearArticleID()
	return _u
}

// SetError sets the "error" field.
func (_u *KBImportJobUpdateOne) SetError(v string) *KBImportJobUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *KBImportJobUpdateOne) SetNillableError(v *string) *KBImportJobUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *KBImportJobUpdateOne) ClearError() *KBImportJobUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KBImportJobUpdateOne) SetUpdatedAt(v time.Time) *KBImportJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the KBImportJobMutation object of the builder.
func (_u *KBImportJobUpdateOne) Mutation() *KBImportJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the KBImportJobUpdate builder.
func (_u *KBImportJobUpdateOne) Where(ps ...predicate.KBImportJob) *KBImportJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KBImportJobUpdateOne) Select(field string, fields ...string) *KBImportJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KBImportJob entity.
func (_u *KBImportJobUpdateOne) Save(ctx context.Context) (*KBImportJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KBImportJobUpdateOne) SaveX(ctx context.Context) *KBImportJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KBImportJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KBImportJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KBImportJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := kbimportjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KBImportJobUpdateOne) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := kbimportjob.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "KBImportJob.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := kbimportjob.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "KBImportJob.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := kbimportjob.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "KBImportJob.title": %w`, err)}
		}
	}
	return nil
}

func (_u *KBImportJobUpdateOne) sqlSave(ctx context.Context) (_node *KBImportJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kbimportjob.Table, kbimportjob.Columns, sqlgraph.NewFieldSpec(kbimportjob.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KBImportJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, kbimportjob.FieldID)
		for _, f := range fields {
			if !kbimportjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != kbimportjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(kbimportjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(kbimportjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.KnowledgeBaseID(); ok {
		_spec.SetField(kbimportjob.FieldKnowledgeBaseID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedKnowledgeBaseID(); ok {
		_spec.AddField(kbimportjob.FieldKnowledgeBaseID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParentNodeID(); ok {
		_spec.SetField(kbimportjob.FieldParentNodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentNodeID(); ok {
		_spec.AddField(kbimportjob.FieldParentNodeID, field.TypeInt64, value)
	}
	if _u.mutation.ParentNodeIDCleared() {
		_spec.ClearField(kbimportjob.FieldParentNodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(kbimportjob.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(kbimportjob.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceKey(); ok {
		_spec.SetField(kbimportjob.FieldSourceKey, field.TypeString, value)
	}
	if _u.mutation.SourceKeyCleared() {
		_spec.ClearField(kbimportjob.FieldSourceKey, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(kbimportjob.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalPages(); ok {
		_spec.SetField(kbimportjob.FieldTotalPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalPages(); ok {
		_spec.AddField(kbimportjob.FieldTotalPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProcessedPages(); ok {
		_spec.SetField(kbimportjob.FieldProcessedPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProcessedPages(); ok {
		_spec.AddField(kbimportjob.FieldProcessedPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(kbimportjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelConfigID(); ok {
		_spec.SetField(kbimportjob.FieldModelConfigID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedModelConfigID(); ok {
		_spec.AddField(kbimportjob.FieldModelConfigID, field.TypeInt64, value)
	}
	if _u.mutation.ModelConfigIDCleared() {
		_spec.ClearField(kbimportjob.FieldModelConfigID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ArticleID(); ok {
		_spec.SetField(kbimportjob.FieldArticleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedArticleID(); ok {
		_spec.AddField(kbimportjob.FieldArticleID, field.TypeInt64, value)
	}
	if _u.mutation.ArticleIDCleared() {
		_spec.ClearField(kbimportjob.FieldArticleID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(kbimportjob.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(kbimportjob.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kbimportjob.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &KBImportJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kbimportjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
