// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ciao1019/Petrichor/apps/api/ent/kbnode"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// KBNodeUpdate is the builder for updating KBNode entities.
type KBNodeUpdate struct {
	config
	hooks    []Hook
	mutation *KBNodeMutation
}

// Where appends a list predicates to the KBNodeUpdate builder.
func (_u *KBNodeUpdate) Where(ps ...predicate.KBNode) *KBNodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *KBNodeUpdate) SetUserID(v int64) *KBNodeUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KBNodeUpdate) SetNillableUserID(v *int64) *KBNodeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *KBNodeUpdate) AddUserID(v int64) *KBNodeUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKnowledgeBaseID sets the "knowledge_base_id" field.
func (_u *KBNodeUpdate) SetKnowledgeBaseID(v int64) *KBNodeUpdate {
	_u.mutation.ResetKnowledgeBaseID()
	_u.mutation.SetKnowledgeBaseID(v)
	return _u
}

// SetNillableKnowledgeBaseID sets the "knowledge_base_id" field if the given value is not nil.
func (_u *KBNodeUpdate) SetNillableKnowledgeBaseID(v *int64) *KBNodeUpdate {
	if v != nil {
		_u.SetKnowledgeBaseID(*v)
	}
	return _u
}

// AddKnowledgeBaseID adds value to the "knowledge_base_id" field.
func (_u *KBNodeUpdate) AddKnowledgeBaseID(v int64) *KBNodeUpdate {
	_u.mutation.AddKnowledgeBaseID(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *KBNodeUpdate) SetParentID(v int64) *KBNodeUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *KBNodeUpdate) SetNillableParentID(v *int64) *KBNodeUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *KBNodeUpdate) AddParentID(v int64) *KBNodeUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *KBNodeUpdate) ClearParentID() *KBNodeUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetType sets the "type" field.
func (_u *KBNodeUpdate) SetType(v string) *KBNodeUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *KBNodeUpdate) SetNillableType(v *string) *KBNodeUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *KBNodeUpdate) SetName(v string) *KBNodeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KBNodeUpdate) SetNillableName(v *string) *KBNodeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *KBNodeUpdate) SetSortOrder(v int) *KBNodeUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *KBNodeUpdate) SetNillableSortOrder(v *int) *KBNodeUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *KBNodeUpdate) AddSortOrder(v int) *KBNodeUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KBNodeUpdate) SetUpdatedAt(v time.Time) *KBNodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the KBNodeMutation object of the builder.
func (_u *KBNodeUpdate) Mutation() *KBNodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KBNodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KBNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KBNodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KBNodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KBNodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := kbnode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KBNodeUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := kbnode.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "KBNode.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := kbnode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "KBNode.name": %w`, err)}
		}
	}
	return nil
}

func (_u *KBNodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kbnode.Table, kbnode.Columns, sqlgraph.NewFieldSpec(kbnode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(kbnode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(kbnode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.KnowledgeBaseID(); ok {
		_spec.SetField(kbnode.FieldKnowledgeBaseID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedKnowledgeBaseID(); ok {
		_spec.AddField(kbnode.FieldKnowledgeBaseID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(kbnode.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(kbnode.FieldParentID, field.TypeInt64, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(kbnode.FieldParentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(kbnode.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(kbnode.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(kbnode.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(kbnode.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kbnode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kbnode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KBNodeUpdateOne is the builder for updating a single KBNode entity.
type KBNodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KBNodeMutation
}

// SetUserID sets the "user_id" field.
func (_u *KBNodeUpdateOne) SetUserID(v int64) *KBNodeUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KBNodeUpdateOne) SetNillableUserID(v *int64) *KBNodeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *KBNodeUpdateOne) AddUserID(v int64) *KBNodeUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKnowledgeBaseID sets the "knowledge_base_id" field.
func (_u *KBNodeUpdateOne) SetKnowledgeBaseID(v int64) *KBNodeUpdateOne {
	_u.mutation.ResetKnowledgeBaseID()
	_u.mutation.SetKnowledgeBaseID(v)
	return _u
}

// SetNillableKnowledgeBaseID sets the "knowledge_base_id" field if the given value is not nil.
func (_u *KBNodeUpdateOne) SetNillableKnowledgeBaseID(v *int64) *KBNodeUpdateOne {
	if v != nil {
		_u.SetKnowledgeBaseID(*v)
	}
	return _u
}

// AddKnowledgeBaseID adds value to the "knowledge_base_id" field.
func (_u *KBNodeUpdateOne) AddKnowledgeBaseID(v int64) *KBNodeUpdateOne {
	_u.mutation.AddKnowledgeBaseID(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *KBNodeUpdateOne) SetParentID(v int64) *KBNodeUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *KBNodeUpdateOne) SetNillableParentID(v *int64) *KBNodeUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *KBNodeUpdateOne) AddParentID(v int64) *KBNodeUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *KBNodeUpdateOne) ClearParentID() *KBNodeUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetType sets the "type" field.
func (_u *KBNodeUpdateOne) SetType(v string) *KBNodeUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *KBNodeUpdateOne) SetNillableType(v *string) *KBNodeUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *KBNodeUpdateOne) SetName(v string) *KBNodeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KBNodeUpdateOne) SetNillableName(v *string) *KBNodeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *KBNodeUpdateOne) SetSortOrder(v int) *KBNodeUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *KBNodeUpdateOne) SetNillableSortOrder(v *int) *KBNodeUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *KBNodeUpdateOne) AddSortOrder(v int) *KBNodeUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KBNodeUpdateOne) SetUpdatedAt(v time.Time) *KBNodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the KBNodeMutation object of the builder.
func (_u *KBNodeUpdateOne) Mutation() *KBNodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the KBNodeUpdate builder.
func (_u *KBNodeUpdateOne) Where(ps ...predicate.KBNode) *KBNodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KBNodeUpdateOne) Select(field string, fields ...string) *KBNodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KBNode entity.
func (_u *KBNodeUpdateOne) Save(ctx context.Context) (*KBNode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KBNodeUpdateOne) SaveX(ctx context.Context) *KBNode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KBNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KBNodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KBNodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := kbnode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KBNodeUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := kbnode.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "KBNode.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := kbnode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "KBNode.name": %w`, err)}
		}
	}
	return nil
}

func (_u *KBNodeUpdateOne) sqlSave(ctx context.Context) (_node *KBNode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kbnode.Table, kbnode.Columns, sqlgraph.NewFieldSpec(kbnode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KBNode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, kbnode.FieldID)
		for _, f := range fields {
			if !kbnode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != kbnode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(kbnode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(kbnode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.KnowledgeBaseID(); ok {
		_spec.SetField(kbnode.FieldKnowledgeBaseID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedKnowledgeBaseID(); ok {
		_spec.AddField(kbnode.FieldKnowledgeBaseID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(kbnode.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(kbnode.FieldParentID, field.TypeInt64, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(kbnode.FieldParentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(kbnode.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(kbnode.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(kbnode.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(kbnode.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kbnode.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &KBNode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kbnode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
