// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Ciao1019/Petrichor/apps/api/ent/kbwikiingestjob"
)

// KBWikiIngestJob is the model entity for the KBWikiIngestJob schema.
type KBWikiIngestJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// KnowledgeBaseID holds the value of the "knowledge_base_id" field.
	KnowledgeBaseID int64 `json:"knowledge_base_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// DocumentIdsJSON holds the value of the "document_ids_json" field.
	DocumentIdsJSON string `json:"document_ids_json,omitempty"`
	// ForceRebuild holds the value of the "force_rebuild" field.
	ForceRebuild bool `json:"force_rebuild,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TotalDocuments holds the value of the "total_documents" field.
	TotalDocuments int `json:"total_documents,omitempty"`
	// ProcessedDocuments holds the value of the "processed_documents" field.
	ProcessedDocuments int `json:"processed_documents,omitempty"`
	// Phase holds the value of the "phase" field.
	Phase string `json:"phase,omitempty"`
	// CurrentDocument holds the value of the "current_document" field.
	CurrentDocument *string `json:"current_document,omitempty"`
	// TotalPages holds the value of the "total_pages" field.
	TotalPages int `json:"total_pages,omitempty"`
	// ProcessedPages holds the value of the "processed_pages" field.
	ProcessedPages int `json:"processed_pages,omitempty"`
	// WarningsJSON holds the value of the "warnings_json" field.
	WarningsJSON string `json:"warnings_json,omitempty"`
	// Error holds the value of the "error" field.
	Error *string `json:"error,omitempty"`
	// AvailableAt holds the value of the "available_at" field.
	AvailableAt time.Time `json:"available_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KBWikiIngestJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case kbwikiingestjob.FieldForceRebuild:
			values[i] = new(sql.NullBool)
		case kbwikiingestjob.FieldID, kbwikiingestjob.FieldUserID, kbwikiingestjob.FieldKnowledgeBaseID, kbwikiingestjob.FieldTotalDocuments, kbwikiingestjob.FieldProcessedDocuments, kbwikiingestjob.FieldTotalPages, kbwikiingestjob.FieldProcessedPages:
			values[i] = new(sql.NullInt64)
		case kbwikiingestjob.FieldKind, kbwikiingestjob.FieldDocumentIdsJSON, kbwikiingestjob.FieldStatus, kbwikiingestjob.FieldPhase, kbwikiingestjob.FieldCurrentDocument, kbwikiingestjob.FieldWarningsJSON, kbwikiingestjob.FieldError:
			values[i] = new(sql.NullString)
		case kbwikiingestjob.FieldAvailableAt, kbwikiingestjob.FieldStartedAt, kbwikiingestjob.FieldFinishedAt, kbwikiingestjob.FieldCreatedAt, kbwikiingestjob.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KBWikiIngestJob fields.
func (_m *KBWikiIngestJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kbwikiingestjob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case kbwikiingestjob.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case kbwikiingestjob.FieldKnowledgeBaseID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field knowledge_base_id", values[i])
			} else if value.Valid {
				_m.KnowledgeBaseID = value.Int64
			}
		case kbwikiingestjob.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case kbwikiingestjob.FieldDocumentIdsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field document_ids_json", values[i])
			} else if value.Valid {
				_m.DocumentIdsJSON = value.String
			}
		case kbwikiingestjob.FieldForceRebuild:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field force_rebuild", values[i])
			} else if value.Valid {
				_m.ForceRebuild = value.Bool
			}
		case kbwikiingestjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case kbwikiingestjob.FieldTotalDocuments:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_documents", values[i])
			} else if value.Valid {
				_m.TotalDocuments = int(value.Int64)
			}
		case kbwikiingestjob.FieldProcessedDocuments:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field processed_documents", values[i])
			} else if value.Valid {
				_m.ProcessedDocuments = int(value.Int64)
			}
		case kbwikiingestjob.FieldPhase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phase", values[i])
			} else if value.Valid {
				_m.Phase = value.String
			}
		case kbwikiingestjob.FieldCurrentDocument:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_document", values[i])
			} else if value.Valid {
				_m.CurrentDocument = new(string)
				*_m.CurrentDocument = value.String
			}
		case kbwikiingestjob.FieldTotalPages:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_pages", values[i])
			} else if value.Valid {
				_m.TotalPages = int(value.Int64)
			}
		case kbwikiingestjob.FieldProcessedPages:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field processed_pages", values[i])
			} else if value.Valid {
				_m.ProcessedPages = int(value.Int64)
			}
		case kbwikiingestjob.FieldWarningsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field warnings_json", values[i])
			} else if value.Valid {
				_m.WarningsJSON = value.String
			}
		case kbwikiingestjob.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = new(string)
				*_m.Error = value.String
			}
		case kbwikiingestjob.FieldAvailableAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field available_at", values[i])
			} else if value.Valid {
				_m.AvailableAt = value.Time
			}
		case kbwikiingestjob.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case kbwikiingestjob.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case kbwikiingestjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case kbwikiingestjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KBWikiIngestJob.
// This includes values selected through modifiers, order, etc.
func (_m *KBWikiIngestJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this KBWikiIngestJob.
// Note that you need to call KBWikiIngestJob.Unwrap() before calling this method if this KBWikiIngestJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KBWikiIngestJob) Update() *KBWikiIngestJobUpdateOne {
	return NewKBWikiIngestJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KBWikiIngestJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KBWikiIngestJob) Unwrap() *KBWikiIngestJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KBWikiIngestJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KBWikiIngestJob) String() string {
	var builder strings.Builder
	builder.WriteString("KBWikiIngestJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("knowledge_base_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.KnowledgeBaseID))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("document_ids_json=")
	builder.WriteString(_m.DocumentIdsJSON)
	builder.WriteString(", ")
	builder.WriteString("force_rebuild=")
	builder.WriteString(fmt.Sprintf("%v", _m.ForceRebuild))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("total_documents=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalDocuments))
	builder.WriteString(", ")
	builder.WriteString("processed_documents=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProcessedDocuments))
	builder.WriteString(", ")
	builder.WriteString("phase=")
	builder.WriteString(_m.Phase)
	builder.WriteString(", ")
	if v := _m.CurrentDocument; v != nil {
		builder.WriteString("current_document=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("total_pages=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalPages))
	builder.WriteString(", ")
	builder.WriteString("processed_pages=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProcessedPages))
	builder.WriteString(", ")
	builder.WriteString("warnings_json=")
	builder.WriteString(_m.WarningsJSON)
	builder.WriteString(", ")
	if v := _m.Error; v != nil {
		builder.WriteString("error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("available_at=")
	builder.WriteString(_m.AvailableAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// KBWikiIngestJobs is a parsable slice of KBWikiIngestJob.
type KBWikiIngestJobs []*KBWikiIngestJob
