// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Ciao1019/Petrichor/apps/api/ent/kbwikidocumentref"
)

// KBWikiDocumentRef is the model entity for the KBWikiDocumentRef schema.
type KBWikiDocumentRef struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// PageID holds the value of the "page_id" field.
	PageID int64 `json:"page_id,omitempty"`
	// DocumentID holds the value of the "document_id" field.
	DocumentID int64 `json:"document_id,omitempty"`
	// ChunkIndexesJSON holds the value of the "chunk_indexes_json" field.
	ChunkIndexesJSON *string `json:"chunk_indexes_json,omitempty"`
	// Note holds the value of the "note" field.
	Note *string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KBWikiDocumentRef) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case kbwikidocumentref.FieldID, kbwikidocumentref.FieldPageID, kbwikidocumentref.FieldDocumentID:
			values[i] = new(sql.NullInt64)
		case kbwikidocumentref.FieldChunkIndexesJSON, kbwikidocumentref.FieldNote:
			values[i] = new(sql.NullString)
		case kbwikidocumentref.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KBWikiDocumentRef fields.
func (_m *KBWikiDocumentRef) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kbwikidocumentref.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case kbwikidocumentref.FieldPageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field page_id", values[i])
			} else if value.Valid {
				_m.PageID = value.Int64
			}
		case kbwikidocumentref.FieldDocumentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field document_id", values[i])
			} else if value.Valid {
				_m.DocumentID = value.Int64
			}
		case kbwikidocumentref.FieldChunkIndexesJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chunk_indexes_json", values[i])
			} else if value.Valid {
				_m.ChunkIndexesJSON = new(string)
				*_m.ChunkIndexesJSON = value.String
			}
		case kbwikidocumentref.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		case kbwikidocumentref.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KBWikiDocumentRef.
// This includes values selected through modifiers, order, etc.
func (_m *KBWikiDocumentRef) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this KBWikiDocumentRef.
// Note that you need to call KBWikiDocumentRef.Unwrap() before calling this method if this KBWikiDocumentRef
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KBWikiDocumentRef) Update() *KBWikiDocumentRefUpdateOne {
	return NewKBWikiDocumentRefClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KBWikiDocumentRef entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KBWikiDocumentRef) Unwrap() *KBWikiDocumentRef {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KBWikiDocumentRef is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KBWikiDocumentRef) String() string {
	var builder strings.Builder
	builder.WriteString("KBWikiDocumentRef(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("page_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PageID))
	builder.WriteString(", ")
	builder.WriteString("document_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DocumentID))
	builder.WriteString(", ")
	if v := _m.ChunkIndexesJSON; v != nil {
		builder.WriteString("chunk_indexes_json=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// KBWikiDocumentRefs is a parsable slice of KBWikiDocumentRef.
type KBWikiDocumentRefs []*KBWikiDocumentRef
