// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ciao1019/Petrichor/apps/api/ent/knowledgebase"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// KnowledgeBaseUpdate is the builder for updating KnowledgeBase entities.
type KnowledgeBaseUpdate struct {
	config
	hooks    []Hook
	mutation *KnowledgeBaseMutation
}

// Where appends a list predicates to the KnowledgeBaseUpdate builder.
func (_u *KnowledgeBaseUpdate) Where(ps ...predicate.KnowledgeBase) *KnowledgeBaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *KnowledgeBaseUpdate) SetUserID(v int64) *KnowledgeBaseUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableUserID(v *int64) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *KnowledgeBaseUpdate) AddUserID(v int64) *KnowledgeBaseUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *KnowledgeBaseUpdate) SetName(v string) *KnowledgeBaseUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableName(v *string) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *KnowledgeBaseUpdate) SetDescription(v string) *KnowledgeBaseUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableDescription(v *string) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *KnowledgeBaseUpdate) ClearDescription() *KnowledgeBaseUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetChunkStrategy sets the "chunk_strategy" field.
func (_u *KnowledgeBaseUpdate) SetChunkStrategy(v string) *KnowledgeBaseUpdate {
	_u.mutation.SetChunkStrategy(v)
	return _u
}

// SetNillableChunkStrategy sets the "chunk_strategy" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableChunkStrategy(v *string) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetChunkStrategy(*v)
	}
	return _u
}

// SetChunkSize sets the "chunk_size" field.
func (_u *KnowledgeBaseUpdate) SetChunkSize(v int) *KnowledgeBaseUpdate {
	_u.mutation.ResetChunkSize()
	_u.mutation.SetChunkSize(v)
	return _u
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableChunkSize(v *int) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetChunkSize(*v)
	}
	return _u
}

// AddChunkSize adds value to the "chunk_size" field.
func (_u *KnowledgeBaseUpdate) AddChunkSize(v int) *KnowledgeBaseUpdate {
	_u.mutation.AddChunkSize(v)
	return _u
}

// SetChunkOverlap sets the "chunk_overlap" field.
func (_u *KnowledgeBaseUpdate) SetChunkOverlap(v int) *KnowledgeBaseUpdate {
	_u.mutation.ResetChunkOverlap()
	_u.mutation.SetChunkOverlap(v)
	return _u
}

// SetNillableChunkOverlap sets the "chunk_overlap" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableChunkOverlap(v *int) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetChunkOverlap(*v)
	}
	return _u
}

// AddChunkOverlap adds value to the "chunk_overlap" field.
func (_u *KnowledgeBaseUpdate) AddChunkOverlap(v int) *KnowledgeBaseUpdate {
	_u.mutation.AddChunkOverlap(v)
	return _u
}

// SetChunkSeparatorsJSON sets the "chunk_separators_json" field.
func (_u *KnowledgeBaseUpdate) SetChunkSeparatorsJSON(v string) *KnowledgeBaseUpdate {
	_u.mutation.SetChunkSeparatorsJSON(v)
	return _u
}

// SetNillableChunkSeparatorsJSON sets the "chunk_separators_json" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableChunkSeparatorsJSON(v *string) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetChunkSeparatorsJSON(*v)
	}
	return _u
}

// ClearChunkSeparatorsJSON clears the value of the "chunk_separators_json" field.
func (_u *KnowledgeBaseUpdate) ClearChunkSeparatorsJSON() *KnowledgeBaseUpdate {
	_u.mutation.ClearChunkSeparatorsJSON()
	return _u
}

// SetEnableParentChild sets the "enable_parent_child" field.
func (_u *KnowledgeBaseUpdate) SetEnableParentChild(v bool) *KnowledgeBaseUpdate {
	_u.mutation.SetEnableParentChild(v)
	return _u
}

// SetNillableEnableParentChild sets the "enable_parent_child" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableEnableParentChild(v *bool) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetEnableParentChild(*v)
	}
	return _u
}

// SetParentChunkSize sets the "parent_chunk_size" field.
func (_u *KnowledgeBaseUpdate) SetParentChunkSize(v int) *KnowledgeBaseUpdate {
	_u.mutation.ResetParentChunkSize()
	_u.mutation.SetParentChunkSize(v)
	return _u
}

// SetNillableParentChunkSize sets the "parent_chunk_size" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableParentChunkSize(v *int) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetParentChunkSize(*v)
	}
	return _u
}

// AddParentChunkSize adds value to the "parent_chunk_size" field.
func (_u *KnowledgeBaseUpdate) AddParentChunkSize(v int) *KnowledgeBaseUpdate {
	_u.mutation.AddParentChunkSize(v)
	return _u
}

// SetChildChunkSize sets the "child_chunk_size" field.
func (_u *KnowledgeBaseUpdate) SetChildChunkSize(v int) *KnowledgeBaseUpdate {
	_u.mutation.ResetChildChunkSize()
	_u.mutation.SetChildChunkSize(v)
	return _u
}

// SetNillableChildChunkSize sets the "child_chunk_size" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableChildChunkSize(v *int) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetChildChunkSize(*v)
	}
	return _u
}

// AddChildChunkSize adds value to the "child_chunk_size" field.
func (_u *KnowledgeBaseUpdate) AddChildChunkSize(v int) *KnowledgeBaseUpdate {
	_u.mutation.AddChildChunkSize(v)
	return _u
}

// SetChatModelID sets the "chat_model_id" field.
func (_u *KnowledgeBaseUpdate) SetChatModelID(v int64) *KnowledgeBaseUpdate {
	_u.mutation.ResetChatModelID()
	_u.mutation.SetChatModelID(v)
	return _u
}

// SetNillableChatModelID sets the "chat_model_id" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableChatModelID(v *int64) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetChatModelID(*v)
	}
	return _u
}

// AddChatModelID adds value to the "chat_model_id" field.
func (_u *KnowledgeBaseUpdate) AddChatModelID(v int64) *KnowledgeBaseUpdate {
	_u.mutation.AddChatModelID(v)
	return _u
}

// ClearChatModelID clears the value of the "chat_model_id" field.
func (_u *KnowledgeBaseUpdate) ClearChatModelID() *KnowledgeBaseUpdate {
	_u.mutation.ClearChatModelID()
	return _u
}

// SetEmbeddingModelID sets the "embedding_model_id" field.
func (_u *KnowledgeBaseUpdate) SetEmbeddingModelID(v int64) *KnowledgeBaseUpdate {
	_u.mutation.ResetEmbeddingModelID()
	_u.mutation.SetEmbeddingModelID(v)
	return _u
}

// SetNillableEmbeddingModelID sets the "embedding_model_id" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableEmbeddingModelID(v *int64) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetEmbeddingModelID(*v)
	}
	return _u
}

// AddEmbeddingModelID adds value to the "embedding_model_id" field.
func (_u *KnowledgeBaseUpdate) AddEmbeddingModelID(v int64) *KnowledgeBaseUpdate {
	_u.mutation.AddEmbeddingModelID(v)
	return _u
}

// ClearEmbeddingModelID clears the value of the "embedding_model_id" field.
func (_u *KnowledgeBaseUpdate) ClearEmbeddingModelID() *KnowledgeBaseUpdate {
	_u.mutation.ClearEmbeddingModelID()
	return _u
}

// SetRerankModelID sets the "rerank_model_id" field.
func (_u *KnowledgeBaseUpdate) SetRerankModelID(v int64) *KnowledgeBaseUpdate {
	_u.mutation.ResetRerankModelID()
	_u.mutation.SetRerankModelID(v)
	return _u
}

// SetNillableRerankModelID sets the "rerank_model_id" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableRerankModelID(v *int64) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetRerankModelID(*v)
	}
	return _u
}

// AddRerankModelID adds value to the "rerank_model_id" field.
func (_u *KnowledgeBaseUpdate) AddRerankModelID(v int64) *KnowledgeBaseUpdate {
	_u.mutation.AddRerankModelID(v)
	return _u
}

// ClearRerankModelID clears the value of the "rerank_model_id" field.
func (_u *KnowledgeBaseUpdate) ClearRerankModelID() *KnowledgeBaseUpdate {
	_u.mutation.ClearRerankModelID()
	return _u
}

// SetWikiEnabled sets the "wiki_enabled" field.
func (_u *KnowledgeBaseUpdate) SetWikiEnabled(v bool) *KnowledgeBaseUpdate {
	_u.mutation.SetWikiEnabled(v)
	return _u
}

// SetNillableWikiEnabled sets the "wiki_enabled" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableWikiEnabled(v *bool) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetWikiEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KnowledgeBaseUpdate) SetUpdatedAt(v time.Time) *KnowledgeBaseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the KnowledgeBaseMutation object of the builder.
func (_u *KnowledgeBaseUpdate) Mutation() *KnowledgeBaseMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KnowledgeBaseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeBaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KnowledgeBaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeBaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KnowledgeBaseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := knowledgebase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeBaseUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := knowledgebase.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.name": %w`, err)}
		}
	}
	return nil
}

func (_u *KnowledgeBaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgebase.Table, knowledgebase.Columns, sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(knowledgebase.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(knowledgebase.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(knowledgebase.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(knowledgebase.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(knowledgebase.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ChunkStrategy(); ok {
		_spec.SetField(knowledgebase.FieldChunkStrategy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChunkSize(); ok {
		_spec.SetField(knowledgebase.FieldChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkSize(); ok {
		_spec.AddField(knowledgebase.FieldChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkOverlap(); ok {
		_spec.SetField(knowledgebase.FieldChunkOverlap, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkOverlap(); ok {
		_spec.AddField(knowledgebase.FieldChunkOverlap, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkSeparatorsJSON(); ok {
		_spec.SetField(knowledgebase.FieldChunkSeparatorsJSON, field.TypeString, value)
	}
	if _u.mutation.ChunkSeparatorsJSONCleared() {
		_spec.ClearField(knowledgebase.FieldChunkSeparatorsJSON, field.TypeString)
	}
	if value, ok := _u.mutation.EnableParentChild(); ok {
		_spec.SetField(knowledgebase.FieldEnableParentChild, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ParentChunkSize(); ok {
		_spec.SetField(knowledgebase.FieldParentChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentChunkSize(); ok {
		_spec.AddField(knowledgebase.FieldParentChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChildChunkSize(); ok {
		_spec.SetField(knowledgebase.FieldChildChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChildChunkSize(); ok {
		_spec.AddField(knowledgebase.FieldChildChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChatModelID(); ok {
		_spec.SetField(knowledgebase.FieldChatModelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatModelID(); ok {
		_spec.AddField(knowledgebase.FieldChatModelID, field.TypeInt64, value)
	}
	if _u.mutation.ChatModelIDCleared() {
		_spec.ClearField(knowledgebase.FieldChatModelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.EmbeddingModelID(); ok {
		_spec.SetField(knowledgebase.FieldEmbeddingModelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEmbeddingModelID(); ok {
		_spec.AddField(knowledgebase.FieldEmbeddingModelID, field.TypeInt64, value)
	}
	if _u.mutation.EmbeddingModelIDCleared() {
		_spec.ClearField(knowledgebase.FieldEmbeddingModelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RerankModelID(); ok {
		_spec.SetField(knowledgebase.FieldRerankModelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRerankModelID(); ok {
		_spec.AddField(knowledgebase.FieldRerankModelID, field.TypeInt64, value)
	}
	if _u.mutation.RerankModelIDCleared() {
		_spec.ClearField(knowledgebase.FieldRerankModelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.WikiEnabled(); ok {
		_spec.SetField(knowledgebase.FieldWikiEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgebase.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgebase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KnowledgeBaseUpdateOne is the builder for updating a single KnowledgeBase entity.
type KnowledgeBaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KnowledgeBaseMutation
}

// SetUserID sets the "user_id" field.
func (_u *KnowledgeBaseUpdateOne) SetUserID(v int64) *KnowledgeBaseUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableUserID(v *int64) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *KnowledgeBaseUpdateOne) AddUserID(v int64) *KnowledgeBaseUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *KnowledgeBaseUpdateOne) SetName(v string) *KnowledgeBaseUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableName(v *string) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *KnowledgeBaseUpdateOne) SetDescription(v string) *KnowledgeBaseUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableDescription(v *string) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *KnowledgeBaseUpdateOne) ClearDescription() *KnowledgeBaseUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetChunkStrategy sets the "chunk_strategy" field.
func (_u *KnowledgeBaseUpdateOne) SetChunkStrategy(v string) *KnowledgeBaseUpdateOne {
	_u.mutation.SetChunkStrategy(v)
	return _u
}

// SetNillableChunkStrategy sets the "chunk_strategy" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableChunkStrategy(v *string) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetChunkStrategy(*v)
	}
	return _u
}

// SetChunkSize sets the "chunk_size" field.
func (_u *KnowledgeBaseUpdateOne) SetChunkSize(v int) *KnowledgeBaseUpdateOne {
	_u.mutation.ResetChunkSize()
	_u.mutation.SetChunkSize(v)
	return _u
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableChunkSize(v *int) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetChunkSize(*v)
	}
	return _u
}

// AddChunkSize adds value to the "chunk_size" field.
func (_u *KnowledgeBaseUpdateOne) AddChunkSize(v int) *KnowledgeBaseUpdateOne {
	_u.mutation.AddChunkSize(v)
	return _u
}

// SetChunkOverlap sets the "chunk_overlap" field.
func (_u *KnowledgeBaseUpdateOne) SetChunkOverlap(v int) *KnowledgeBaseUpdateOne {
	_u.mutation.ResetChunkOverlap()
	_u.mutation.SetChunkOverlap(v)
	return _u
}

// SetNillableChunkOverlap sets the "chunk_overlap" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableChunkOverlap(v *int) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetChunkOverlap(*v)
	}
	return _u
}

// AddChunkOverlap adds value to the "chunk_overlap" field.
func (_u *KnowledgeBaseUpdateOne) AddChunkOverlap(v int) *KnowledgeBaseUpdateOne {
	_u.mutation.AddChunkOverlap(v)
	return _u
}

// SetChunkSeparatorsJSON sets the "chunk_separators_json" field.
func (_u *KnowledgeBaseUpdateOne) SetChunkSeparatorsJSON(v string) *KnowledgeBaseUpdateOne {
	_u.mutation.SetChunkSeparatorsJSON(v)
	return _u
}

// SetNillableChunkSeparatorsJSON sets the "chunk_separators_json" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableChunkSeparatorsJSON(v *string) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetChunkSeparatorsJSON(*v)
	}
	return _u
}

// ClearChunkSeparatorsJSON clears the value of the "chunk_separators_json" field.
func (_u *KnowledgeBaseUpdateOne) ClearChunkSeparatorsJSON() *KnowledgeBaseUpdateOne {
	_u.mutation.ClearChunkSeparatorsJSON()
	return _u
}

// SetEnableParentChild sets the "enable_parent_child" field.
func (_u *KnowledgeBaseUpdateOne) SetEnableParentChild(v bool) *KnowledgeBaseUpdateOne {
	_u.mutation.SetEnableParentChild(v)
	return _u
}

// SetNillableEnableParentChild sets the "enable_parent_child" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableEnableParentChild(v *bool) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetEnableParentChild(*v)
	}
	return _u
}

// SetParentChunkSize sets the "parent_chunk_size" field.
func (_u *KnowledgeBaseUpdateOne) SetParentChunkSize(v int) *KnowledgeBaseUpdateOne {
	_u.mutation.ResetParentChunkSize()
	_u.mutation.SetParentChunkSize(v)
	return _u
}

// SetNillableParentChunkSize sets the "parent_chunk_size" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableParentChunkSize(v *int) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetParentChunkSize(*v)
	}
	return _u
}

// AddParentChunkSize adds value to the "parent_chunk_size" field.
func (_u *KnowledgeBaseUpdateOne) AddParentChunkSize(v int) *KnowledgeBaseUpdateOne {
	_u.mutation.AddParentChunkSize(v)
	return _u
}

// SetChildChunkSize sets the "child_chunk_size" field.
func (_u *KnowledgeBaseUpdateOne) SetChildChunkSize(v int) *KnowledgeBaseUpdateOne {
	_u.mutation.ResetChildChunkSize()
	_u.mutation.SetChildChunkSize(v)
	return _u
}

// SetNillableChildChunkSize sets the "child_chunk_size" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableChildChunkSize(v *int) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetChildChunkSize(*v)
	}
	return _u
}

// AddChildChunkSize adds value to the "child_chunk_size" field.
func (_u *KnowledgeBaseUpdateOne) AddChildChunkSize(v int) *KnowledgeBaseUpdateOne {
	_u.mutation.AddChildChunkSize(v)
	return _u
}

// SetChatModelID sets the "chat_model_id" field.
func (_u *KnowledgeBaseUpdateOne) SetChatModelID(v int64) *KnowledgeBaseUpdateOne {
	_u.mutation.ResetChatModelID()
	_u.mutation.SetChatModelID(v)
	return _u
}

// SetNillableChatModelID sets the "chat_model_id" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableChatModelID(v *int64) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetChatModelID(*v)
	}
	return _u
}

// AddChatModelID adds value to the "chat_model_id" field.
func (_u *KnowledgeBaseUpdateOne) AddChatModelID(v int64) *KnowledgeBaseUpdateOne {
	_u.mutation.AddChatModelID(v)
	return _u
}

// ClearChatModelID clears the value of the "chat_model_id" field.
func (_u *KnowledgeBaseUpdateOne) ClearChatModelID() *KnowledgeBaseUpdateOne {
	_u.mutation.ClearChatModelID()
	return _u
}

// SetEmbeddingModelID sets the "embedding_model_id" field.
func (_u *KnowledgeBaseUpdateOne) SetEmbeddingModelID(v int64) *KnowledgeBaseUpdateOne {
	_u.mutation.ResetEmbeddingModelID()
	_u.mutation.SetEmbeddingModelID(v)
	return _u
}

// SetNillableEmbeddingModelID sets the "embedding_model_id" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableEmbeddingModelID(v *int64) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetEmbeddingModelID(*v)
	}
	return _u
}

// AddEmbeddingModelID adds value to the "embedding_model_id" field.
func (_u *KnowledgeBaseUpdateOne) AddEmbeddingModelID(v int64) *KnowledgeBaseUpdateOne {
	_u.mutation.AddEmbeddingModelID(v)
	return _u
}

// ClearEmbeddingModelID clears the value of the "embedding_model_id" field.
func (_u *KnowledgeBaseUpdateOne) ClearEmbeddingModelID() *KnowledgeBaseUpdateOne {
	_u.mutation.ClearEmbeddingModelID()
	return _u
}

// SetRerankModelID sets the "rerank_model_id" field.
func (_u *KnowledgeBaseUpdateOne) SetRerankModelID(v int64) *KnowledgeBaseUpdateOne {
	_u.mutation.ResetRerankModelID()
	_u.mutation.SetRerankModelID(v)
	return _u
}

// SetNillableRerankModelID sets the "rerank_model_id" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableRerankModelID(v *int64) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetRerankModelID(*v)
	}
	return _u
}

// AddRerankModelID adds value to the "rerank_model_id" field.
func (_u *KnowledgeBaseUpdateOne) AddRerankModelID(v int64) *KnowledgeBaseUpdateOne {
	_u.mutation.AddRerankModelID(v)
	return _u
}

// ClearRerankModelID clears the value of the "rerank_model_id" field.
func (_u *KnowledgeBaseUpdateOne) ClearRerankModelID() *KnowledgeBaseUpdateOne {
	_u.mutation.ClearRerankModelID()
	return _u
}

// SetWikiEnabled sets the "wiki_enabled" field.
func (_u *KnowledgeBaseUpdateOne) SetWikiEnabled(v bool) *KnowledgeBaseUpdateOne {
	_u.mutation.SetWikiEnabled(v)
	return _u
}

// SetNillableWikiEnabled sets the "wiki_enabled" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableWikiEnabled(v *bool) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetWikiEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KnowledgeBaseUpdateOne) SetUpdatedAt(v time.Time) *KnowledgeBaseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the KnowledgeBaseMutation object of the builder.
func (_u *KnowledgeBaseUpdateOne) Mutation() *KnowledgeBaseMutation {
	return _u.mutation
}

// Where appends a list predicates to the KnowledgeBaseUpdate builder.
func (_u *KnowledgeBaseUpdateOne) Where(ps ...predicate.KnowledgeBase) *KnowledgeBaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KnowledgeBaseUpdateOne) Select(field string, fields ...string) *KnowledgeBaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KnowledgeBase entity.
func (_u *KnowledgeBaseUpdateOne) Save(ctx context.Context) (*KnowledgeBase, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeBaseUpdateOne) SaveX(ctx context.Context) *KnowledgeBase {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KnowledgeBaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeBaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KnowledgeBaseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := knowledgebase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeBaseUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := knowledgebase.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.name": %w`, err)}
		}
	}
	return nil
}

func (_u *KnowledgeBaseUpdateOne) sqlSave(ctx context.Context) (_node *KnowledgeBase, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgebase.Table, knowledgebase.Columns, sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KnowledgeBase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, knowledgebase.FieldID)
		for _, f := range fields {
			if !knowledgebase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != knowledgebase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(knowledgebase.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(knowledgebase.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(knowledgebase.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(knowledgebase.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(knowledgebase.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ChunkStrategy(); ok {
		_spec.SetField(knowledgebase.FieldChunkStrategy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChunkSize(); ok {
		_spec.SetField(knowledgebase.FieldChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkSize(); ok {
		_spec.AddField(knowledgebase.FieldChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkOverlap(); ok {
		_spec.SetField(knowledgebase.FieldChunkOverlap, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkOverlap(); ok {
		_spec.AddField(knowledgebase.FieldChunkOverlap, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkSeparatorsJSON(); ok {
		_spec.SetField(knowledgebase.FieldChunkSeparatorsJSON, field.TypeString, value)
	}
	if _u.mutation.ChunkSeparatorsJSONCleared() {
		_spec.ClearField(knowledgebase.FieldChunkSeparatorsJSON, field.TypeString)
	}
	if value, ok := _u.mutation.EnableParentChild(); ok {
		_spec.SetField(knowledgebase.FieldEnableParentChild, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ParentChunkSize(); ok {
		_spec.SetField(knowledgebase.FieldParentChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentChunkSize(); ok {
		_spec.AddField(knowledgebase.FieldParentChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChildChunkSize(); ok {
		_spec.SetField(knowledgebase.FieldChildChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChildChunkSize(); ok {
		_spec.AddField(knowledgebase.FieldChildChunkSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChatModelID(); ok {
		_spec.SetField(knowledgebase.FieldChatModelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatModelID(); ok {
		_spec.AddField(knowledgebase.FieldChatModelID, field.TypeInt64, value)
	}
	if _u.mutation.ChatModelIDCleared() {
		_spec.ClearField(knowledgebase.FieldChatModelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.EmbeddingModelID(); ok {
		_spec.SetField(knowledgebase.FieldEmbeddingModelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEmbeddingModelID(); ok {
		_spec.AddField(knowledgebase.FieldEmbeddingModelID, field.TypeInt64, value)
	}
	if _u.mutation.EmbeddingModelIDCleared() {
		_spec.ClearField(knowledgebase.FieldEmbeddingModelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RerankModelID(); ok {
		_spec.SetField(knowledgebase.FieldRerankModelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRerankModelID(); ok {
		_spec.AddField(knowledgebase.FieldRerankModelID, field.TypeInt64, value)
	}
	if _u.mutation.RerankModelIDCleared() {
		_spec.ClearField(knowledgebase.FieldRerankModelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.WikiEnabled(); ok {
		_spec.SetField(knowledgebase.FieldWikiEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgebase.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &KnowledgeBase{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgebase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
