// Code generated by ent, DO NOT EDIT.

package kbimportjobpage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLTE(FieldID, id))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldJobID, v))
}

// PageNo applies equality check predicate on the "page_no" field. It's identical to PageNoEQ.
func PageNo(v int) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldPageNo, v))
}

// ImageKey applies equality check predicate on the "image_key" field. It's identical to ImageKeyEQ.
func ImageKey(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldImageKey, v))
}

// ExtractedBy applies equality check predicate on the "extracted_by" field. It's identical to ExtractedByEQ.
func ExtractedBy(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldExtractedBy, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldStatus, v))
}

// Markdown applies equality check predicate on the "markdown" field. It's identical to MarkdownEQ.
func Markdown(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldMarkdown, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldUpdatedAt, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v int64) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLTE(FieldJobID, v))
}

// PageNoEQ applies the EQ predicate on the "page_no" field.
func PageNoEQ(v int) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldPageNo, v))
}

// PageNoNEQ applies the NEQ predicate on the "page_no" field.
func PageNoNEQ(v int) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNEQ(FieldPageNo, v))
}

// PageNoIn applies the In predicate on the "page_no" field.
func PageNoIn(vs ...int) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIn(FieldPageNo, vs...))
}

// PageNoNotIn applies the NotIn predicate on the "page_no" field.
func PageNoNotIn(vs ...int) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotIn(FieldPageNo, vs...))
}

// PageNoGT applies the GT predicate on the "page_no" field.
func PageNoGT(v int) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGT(FieldPageNo, v))
}

// PageNoGTE applies the GTE predicate on the "page_no" field.
func PageNoGTE(v int) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGTE(FieldPageNo, v))
}

// PageNoLT applies the LT predicate on the "page_no" field.
func PageNoLT(v int) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLT(FieldPageNo, v))
}

// PageNoLTE applies the LTE predicate on the "page_no" field.
func PageNoLTE(v int) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLTE(FieldPageNo, v))
}

// ImageKeyEQ applies the EQ predicate on the "image_key" field.
func ImageKeyEQ(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldImageKey, v))
}

// ImageKeyNEQ applies the NEQ predicate on the "image_key" field.
func ImageKeyNEQ(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNEQ(FieldImageKey, v))
}

// ImageKeyIn applies the In predicate on the "image_key" field.
func ImageKeyIn(vs ...string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIn(FieldImageKey, vs...))
}

// ImageKeyNotIn applies the NotIn predicate on the "image_key" field.
func ImageKeyNotIn(vs ...string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotIn(FieldImageKey, vs...))
}

// ImageKeyGT applies the GT predicate on the "image_key" field.
func ImageKeyGT(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGT(FieldImageKey, v))
}

// ImageKeyGTE applies the GTE predicate on the "image_key" field.
func ImageKeyGTE(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGTE(FieldImageKey, v))
}

// ImageKeyLT applies the LT predicate on the "image_key" field.
func ImageKeyLT(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLT(FieldImageKey, v))
}

// ImageKeyLTE applies the LTE predicate on the "image_key" field.
func ImageKeyLTE(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLTE(FieldImageKey, v))
}

// ImageKeyContains applies the Contains predicate on the "image_key" field.
func ImageKeyContains(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldContains(FieldImageKey, v))
}

// ImageKeyHasPrefix applies the HasPrefix predicate on the "image_key" field.
func ImageKeyHasPrefix(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldHasPrefix(FieldImageKey, v))
}

// ImageKeyHasSuffix applies the HasSuffix predicate on the "image_key" field.
func ImageKeyHasSuffix(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldHasSuffix(FieldImageKey, v))
}

// ImageKeyIsNil applies the IsNil predicate on the "image_key" field.
func ImageKeyIsNil() predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIsNull(FieldImageKey))
}

// ImageKeyNotNil applies the NotNil predicate on the "image_key" field.
func ImageKeyNotNil() predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotNull(FieldImageKey))
}

// ImageKeyEqualFold applies the EqualFold predicate on the "image_key" field.
func ImageKeyEqualFold(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEqualFold(FieldImageKey, v))
}

// ImageKeyContainsFold applies the ContainsFold predicate on the "image_key" field.
func ImageKeyContainsFold(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldContainsFold(FieldImageKey, v))
}

// ExtractedByEQ applies the EQ predicate on the "extracted_by" field.
func ExtractedByEQ(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldExtractedBy, v))
}

// ExtractedByNEQ applies the NEQ predicate on the "extracted_by" field.
func ExtractedByNEQ(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNEQ(FieldExtractedBy, v))
}

// ExtractedByIn applies the In predicate on the "extracted_by" field.
func ExtractedByIn(vs ...string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIn(FieldExtractedBy, vs...))
}

// ExtractedByNotIn applies the NotIn predicate on the "extracted_by" field.
func ExtractedByNotIn(vs ...string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotIn(FieldExtractedBy, vs...))
}

// ExtractedByGT applies the GT predicate on the "extracted_by" field.
func ExtractedByGT(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGT(FieldExtractedBy, v))
}

// ExtractedByGTE applies the GTE predicate on the "extracted_by" field.
func ExtractedByGTE(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGTE(FieldExtractedBy, v))
}

// ExtractedByLT applies the LT predicate on the "extracted_by" field.
func ExtractedByLT(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLT(FieldExtractedBy, v))
}

// ExtractedByLTE applies the LTE predicate on the "extracted_by" field.
func ExtractedByLTE(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLTE(FieldExtractedBy, v))
}

// ExtractedByContains applies the Contains predicate on the "extracted_by" field.
func ExtractedByContains(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldContains(FieldExtractedBy, v))
}

// ExtractedByHasPrefix applies the HasPrefix predicate on the "extracted_by" field.
func ExtractedByHasPrefix(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldHasPrefix(FieldExtractedBy, v))
}

// ExtractedByHasSuffix applies the HasSuffix predicate on the "extracted_by" field.
func ExtractedByHasSuffix(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldHasSuffix(FieldExtractedBy, v))
}

// ExtractedByEqualFold applies the EqualFold predicate on the "extracted_by" field.
func ExtractedByEqualFold(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEqualFold(FieldExtractedBy, v))
}

// ExtractedByContainsFold applies the ContainsFold predicate on the "extracted_by" field.
func ExtractedByContainsFold(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldContainsFold(FieldExtractedBy, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldContainsFold(FieldStatus, v))
}

// MarkdownEQ applies the EQ predicate on the "markdown" field.
func MarkdownEQ(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldMarkdown, v))
}

// MarkdownNEQ applies the NEQ predicate on the "markdown" field.
func MarkdownNEQ(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNEQ(FieldMarkdown, v))
}

// MarkdownIn applies the In predicate on the "markdown" field.
func MarkdownIn(vs ...string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIn(FieldMarkdown, vs...))
}

// MarkdownNotIn applies the NotIn predicate on the "markdown" field.
func MarkdownNotIn(vs ...string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotIn(FieldMarkdown, vs...))
}

// MarkdownGT applies the GT predicate on the "markdown" field.
func MarkdownGT(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGT(FieldMarkdown, v))
}

// MarkdownGTE applies the GTE predicate on the "markdown" field.
func MarkdownGTE(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGTE(FieldMarkdown, v))
}

// MarkdownLT applies the LT predicate on the "markdown" field.
func MarkdownLT(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLT(FieldMarkdown, v))
}

// MarkdownLTE applies the LTE predicate on the "markdown" field.
func MarkdownLTE(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLTE(FieldMarkdown, v))
}

// MarkdownContains applies the Contains predicate on the "markdown" field.
func MarkdownContains(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldContains(FieldMarkdown, v))
}

// MarkdownHasPrefix applies the HasPrefix predicate on the "markdown" field.
func MarkdownHasPrefix(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldHasPrefix(FieldMarkdown, v))
}

// MarkdownHasSuffix applies the HasSuffix predicate on the "markdown" field.
func MarkdownHasSuffix(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldHasSuffix(FieldMarkdown, v))
}

// MarkdownIsNil applies the IsNil predicate on the "markdown" field.
func MarkdownIsNil() predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIsNull(FieldMarkdown))
}

// MarkdownNotNil applies the NotNil predicate on the "markdown" field.
func MarkdownNotNil() predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotNull(FieldMarkdown))
}

// MarkdownEqualFold applies the EqualFold predicate on the "markdown" field.
func MarkdownEqualFold(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEqualFold(FieldMarkdown, v))
}

// MarkdownContainsFold applies the ContainsFold predicate on the "markdown" field.
func MarkdownContainsFold(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldContainsFold(FieldMarkdown, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldContainsFold(FieldError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KBImportJobPage) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KBImportJobPage) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KBImportJobPage) predicate.KBImportJobPage {
	return predicate.KBImportJobPage(sql.NotPredicates(p))
}
