// Code generated by ent, DO NOT EDIT.

package kbdocumentchunk

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the kbdocumentchunk type in the database.
	Label = "kb_document_chunk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldKnowledgeBaseID holds the string denoting the knowledge_base_id field in the database.
	FieldKnowledgeBaseID = "knowledge_base_id"
	// FieldDocumentID holds the string denoting the document_id field in the database.
	FieldDocumentID = "document_id"
	// FieldChunkIndex holds the string denoting the chunk_index field in the database.
	FieldChunkIndex = "chunk_index"
	// FieldLocator holds the string denoting the locator field in the database.
	FieldLocator = "locator"
	// FieldPage holds the string denoting the page field in the database.
	FieldPage = "page"
	// FieldContextHeader holds the string denoting the context_header field in the database.
	FieldContextHeader = "context_header"
	// FieldStartOffset holds the string denoting the start_offset field in the database.
	FieldStartOffset = "start_offset"
	// FieldEndOffset holds the string denoting the end_offset field in the database.
	FieldEndOffset = "end_offset"
	// FieldChunkType holds the string denoting the chunk_type field in the database.
	FieldChunkType = "chunk_type"
	// FieldParentChunkIndex holds the string denoting the parent_chunk_index field in the database.
	FieldParentChunkIndex = "parent_chunk_index"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldCharCount holds the string denoting the char_count field in the database.
	FieldCharCount = "char_count"
	// FieldTokenEstimate holds the string denoting the token_estimate field in the database.
	FieldTokenEstimate = "token_estimate"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the kbdocumentchunk in the database.
	Table = "petrichor_kb_document_chunk"
)

// Columns holds all SQL columns for kbdocumentchunk fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldKnowledgeBaseID,
	FieldDocumentID,
	FieldChunkIndex,
	FieldLocator,
	FieldPage,
	FieldContextHeader,
	FieldStartOffset,
	FieldEndOffset,
	FieldChunkType,
	FieldParentChunkIndex,
	FieldText,
	FieldCharCount,
	FieldTokenEstimate,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultChunkType holds the default value on creation for the "chunk_type" field.
	DefaultChunkType string
	// TextValidator is a validator for the "text" field. It is called by the builders before save.
	TextValidator func(string) error
	// DefaultCharCount holds the default value on creation for the "char_count" field.
	DefaultCharCount int
	// DefaultTokenEstimate holds the default value on creation for the "token_estimate" field.
	DefaultTokenEstimate int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the KBDocumentChunk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByKnowledgeBaseID orders the results by the knowledge_base_id field.
func ByKnowledgeBaseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKnowledgeBaseID, opts...).ToFunc()
}

// ByDocumentID orders the results by the document_id field.
func ByDocumentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentID, opts...).ToFunc()
}

// ByChunkIndex orders the results by the chunk_index field.
func ByChunkIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkIndex, opts...).ToFunc()
}

// ByLocator orders the results by the locator field.
func ByLocator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocator, opts...).ToFunc()
}

// ByPage orders the results by the page field.
func ByPage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPage, opts...).ToFunc()
}

// ByContextHeader orders the results by the context_header field.
func ByContextHeader(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextHeader, opts...).ToFunc()
}

// ByStartOffset orders the results by the start_offset field.
func ByStartOffset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartOffset, opts...).ToFunc()
}

// ByEndOffset orders the results by the end_offset field.
func ByEndOffset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndOffset, opts...).ToFunc()
}

// ByChunkType orders the results by the chunk_type field.
func ByChunkType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkType, opts...).ToFunc()
}

// ByParentChunkIndex orders the results by the parent_chunk_index field.
func ByParentChunkIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentChunkIndex, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// ByCharCount orders the results by the char_count field.
func ByCharCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCharCount, opts...).ToFunc()
}

// ByTokenEstimate orders the results by the token_estimate field.
func ByTokenEstimate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenEstimate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
