// Code generated by ent, DO NOT EDIT.

package kbdocumentchunk

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldUserID, v))
}

// KnowledgeBaseID applies equality check predicate on the "knowledge_base_id" field. It's identical to KnowledgeBaseIDEQ.
func KnowledgeBaseID(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldKnowledgeBaseID, v))
}

// DocumentID applies equality check predicate on the "document_id" field. It's identical to DocumentIDEQ.
func DocumentID(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldDocumentID, v))
}

// ChunkIndex applies equality check predicate on the "chunk_index" field. It's identical to ChunkIndexEQ.
func ChunkIndex(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldChunkIndex, v))
}

// Locator applies equality check predicate on the "locator" field. It's identical to LocatorEQ.
func Locator(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldLocator, v))
}

// Page applies equality check predicate on the "page" field. It's identical to PageEQ.
func Page(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldPage, v))
}

// ContextHeader applies equality check predicate on the "context_header" field. It's identical to ContextHeaderEQ.
func ContextHeader(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldContextHeader, v))
}

// StartOffset applies equality check predicate on the "start_offset" field. It's identical to StartOffsetEQ.
func StartOffset(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldStartOffset, v))
}

// EndOffset applies equality check predicate on the "end_offset" field. It's identical to EndOffsetEQ.
func EndOffset(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldEndOffset, v))
}

// ChunkType applies equality check predicate on the "chunk_type" field. It's identical to ChunkTypeEQ.
func ChunkType(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldChunkType, v))
}

// ParentChunkIndex applies equality check predicate on the "parent_chunk_index" field. It's identical to ParentChunkIndexEQ.
func ParentChunkIndex(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldParentChunkIndex, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldText, v))
}

// CharCount applies equality check predicate on the "char_count" field. It's identical to CharCountEQ.
func CharCount(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldCharCount, v))
}

// TokenEstimate applies equality check predicate on the "token_estimate" field. It's identical to TokenEstimateEQ.
func TokenEstimate(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldTokenEstimate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldUserID, v))
}

// KnowledgeBaseIDEQ applies the EQ predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDEQ(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDNEQ applies the NEQ predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDNEQ(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDIn applies the In predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDIn(vs ...int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldKnowledgeBaseID, vs...))
}

// KnowledgeBaseIDNotIn applies the NotIn predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDNotIn(vs ...int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldKnowledgeBaseID, vs...))
}

// KnowledgeBaseIDGT applies the GT predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDGT(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDGTE applies the GTE predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDGTE(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDLT applies the LT predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDLT(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDLTE applies the LTE predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDLTE(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldKnowledgeBaseID, v))
}

// DocumentIDEQ applies the EQ predicate on the "document_id" field.
func DocumentIDEQ(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldDocumentID, v))
}

// DocumentIDNEQ applies the NEQ predicate on the "document_id" field.
func DocumentIDNEQ(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldDocumentID, v))
}

// DocumentIDIn applies the In predicate on the "document_id" field.
func DocumentIDIn(vs ...int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldDocumentID, vs...))
}

// DocumentIDNotIn applies the NotIn predicate on the "document_id" field.
func DocumentIDNotIn(vs ...int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldDocumentID, vs...))
}

// DocumentIDGT applies the GT predicate on the "document_id" field.
func DocumentIDGT(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldDocumentID, v))
}

// DocumentIDGTE applies the GTE predicate on the "document_id" field.
func DocumentIDGTE(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldDocumentID, v))
}

// DocumentIDLT applies the LT predicate on the "document_id" field.
func DocumentIDLT(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldDocumentID, v))
}

// DocumentIDLTE applies the LTE predicate on the "document_id" field.
func DocumentIDLTE(v int64) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldDocumentID, v))
}

// ChunkIndexEQ applies the EQ predicate on the "chunk_index" field.
func ChunkIndexEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldChunkIndex, v))
}

// ChunkIndexNEQ applies the NEQ predicate on the "chunk_index" field.
func ChunkIndexNEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldChunkIndex, v))
}

// ChunkIndexIn applies the In predicate on the "chunk_index" field.
func ChunkIndexIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldChunkIndex, vs...))
}

// ChunkIndexNotIn applies the NotIn predicate on the "chunk_index" field.
func ChunkIndexNotIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldChunkIndex, vs...))
}

// ChunkIndexGT applies the GT predicate on the "chunk_index" field.
func ChunkIndexGT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldChunkIndex, v))
}

// ChunkIndexGTE applies the GTE predicate on the "chunk_index" field.
func ChunkIndexGTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldChunkIndex, v))
}

// ChunkIndexLT applies the LT predicate on the "chunk_index" field.
func ChunkIndexLT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldChunkIndex, v))
}

// ChunkIndexLTE applies the LTE predicate on the "chunk_index" field.
func ChunkIndexLTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldChunkIndex, v))
}

// LocatorEQ applies the EQ predicate on the "locator" field.
func LocatorEQ(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldLocator, v))
}

// LocatorNEQ applies the NEQ predicate on the "locator" field.
func LocatorNEQ(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldLocator, v))
}

// LocatorIn applies the In predicate on the "locator" field.
func LocatorIn(vs ...string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldLocator, vs...))
}

// LocatorNotIn applies the NotIn predicate on the "locator" field.
func LocatorNotIn(vs ...string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldLocator, vs...))
}

// LocatorGT applies the GT predicate on the "locator" field.
func LocatorGT(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldLocator, v))
}

// LocatorGTE applies the GTE predicate on the "locator" field.
func LocatorGTE(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldLocator, v))
}

// LocatorLT applies the LT predicate on the "locator" field.
func LocatorLT(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldLocator, v))
}

// LocatorLTE applies the LTE predicate on the "locator" field.
func LocatorLTE(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldLocator, v))
}

// LocatorContains applies the Contains predicate on the "locator" field.
func LocatorContains(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldContains(FieldLocator, v))
}

// LocatorHasPrefix applies the HasPrefix predicate on the "locator" field.
func LocatorHasPrefix(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldHasPrefix(FieldLocator, v))
}

// LocatorHasSuffix applies the HasSuffix predicate on the "locator" field.
func LocatorHasSuffix(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldHasSuffix(FieldLocator, v))
}

// LocatorIsNil applies the IsNil predicate on the "locator" field.
func LocatorIsNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIsNull(FieldLocator))
}

// LocatorNotNil applies the NotNil predicate on the "locator" field.
func LocatorNotNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotNull(FieldLocator))
}

// LocatorEqualFold applies the EqualFold predicate on the "locator" field.
func LocatorEqualFold(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEqualFold(FieldLocator, v))
}

// LocatorContainsFold applies the ContainsFold predicate on the "locator" field.
func LocatorContainsFold(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldContainsFold(FieldLocator, v))
}

// PageEQ applies the EQ predicate on the "page" field.
func PageEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldPage, v))
}

// PageNEQ applies the NEQ predicate on the "page" field.
func PageNEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldPage, v))
}

// PageIn applies the In predicate on the "page" field.
func PageIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldPage, vs...))
}

// PageNotIn applies the NotIn predicate on the "page" field.
func PageNotIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldPage, vs...))
}

// PageGT applies the GT predicate on the "page" field.
func PageGT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldPage, v))
}

// PageGTE applies the GTE predicate on the "page" field.
func PageGTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldPage, v))
}

// PageLT applies the LT predicate on the "page" field.
func PageLT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldPage, v))
}

// PageLTE applies the LTE predicate on the "page" field.
func PageLTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldPage, v))
}

// PageIsNil applies the IsNil predicate on the "page" field.
func PageIsNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIsNull(FieldPage))
}

// PageNotNil applies the NotNil predicate on the "page" field.
func PageNotNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotNull(FieldPage))
}

// ContextHeaderEQ applies the EQ predicate on the "context_header" field.
func ContextHeaderEQ(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldContextHeader, v))
}

// ContextHeaderNEQ applies the NEQ predicate on the "context_header" field.
func ContextHeaderNEQ(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldContextHeader, v))
}

// ContextHeaderIn applies the In predicate on the "context_header" field.
func ContextHeaderIn(vs ...string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldContextHeader, vs...))
}

// ContextHeaderNotIn applies the NotIn predicate on the "context_header" field.
func ContextHeaderNotIn(vs ...string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldContextHeader, vs...))
}

// ContextHeaderGT applies the GT predicate on the "context_header" field.
func ContextHeaderGT(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldContextHeader, v))
}

// ContextHeaderGTE applies the GTE predicate on the "context_header" field.
func ContextHeaderGTE(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldContextHeader, v))
}

// ContextHeaderLT applies the LT predicate on the "context_header" field.
func ContextHeaderLT(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldContextHeader, v))
}

// ContextHeaderLTE applies the LTE predicate on the "context_header" field.
func ContextHeaderLTE(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldContextHeader, v))
}

// ContextHeaderContains applies the Contains predicate on the "context_header" field.
func ContextHeaderContains(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldContains(FieldContextHeader, v))
}

// ContextHeaderHasPrefix applies the HasPrefix predicate on the "context_header" field.
func ContextHeaderHasPrefix(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldHasPrefix(FieldContextHeader, v))
}

// ContextHeaderHasSuffix applies the HasSuffix predicate on the "context_header" field.
func ContextHeaderHasSuffix(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldHasSuffix(FieldContextHeader, v))
}

// ContextHeaderIsNil applies the IsNil predicate on the "context_header" field.
func ContextHeaderIsNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIsNull(FieldContextHeader))
}

// ContextHeaderNotNil applies the NotNil predicate on the "context_header" field.
func ContextHeaderNotNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotNull(FieldContextHeader))
}

// ContextHeaderEqualFold applies the EqualFold predicate on the "context_header" field.
func ContextHeaderEqualFold(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEqualFold(FieldContextHeader, v))
}

// ContextHeaderContainsFold applies the ContainsFold predicate on the "context_header" field.
func ContextHeaderContainsFold(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldContainsFold(FieldContextHeader, v))
}

// StartOffsetEQ applies the EQ predicate on the "start_offset" field.
func StartOffsetEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldStartOffset, v))
}

// StartOffsetNEQ applies the NEQ predicate on the "start_offset" field.
func StartOffsetNEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldStartOffset, v))
}

// StartOffsetIn applies the In predicate on the "start_offset" field.
func StartOffsetIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldStartOffset, vs...))
}

// StartOffsetNotIn applies the NotIn predicate on the "start_offset" field.
func StartOffsetNotIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldStartOffset, vs...))
}

// StartOffsetGT applies the GT predicate on the "start_offset" field.
func StartOffsetGT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldStartOffset, v))
}

// StartOffsetGTE applies the GTE predicate on the "start_offset" field.
func StartOffsetGTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldStartOffset, v))
}

// StartOffsetLT applies the LT predicate on the "start_offset" field.
func StartOffsetLT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldStartOffset, v))
}

// StartOffsetLTE applies the LTE predicate on the "start_offset" field.
func StartOffsetLTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldStartOffset, v))
}

// StartOffsetIsNil applies the IsNil predicate on the "start_offset" field.
func StartOffsetIsNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIsNull(FieldStartOffset))
}

// StartOffsetNotNil applies the NotNil predicate on the "start_offset" field.
func StartOffsetNotNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotNull(FieldStartOffset))
}

// EndOffsetEQ applies the EQ predicate on the "end_offset" field.
func EndOffsetEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldEndOffset, v))
}

// EndOffsetNEQ applies the NEQ predicate on the "end_offset" field.
func EndOffsetNEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldEndOffset, v))
}

// EndOffsetIn applies the In predicate on the "end_offset" field.
func EndOffsetIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldEndOffset, vs...))
}

// EndOffsetNotIn applies the NotIn predicate on the "end_offset" field.
func EndOffsetNotIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldEndOffset, vs...))
}

// EndOffsetGT applies the GT predicate on the "end_offset" field.
func EndOffsetGT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldEndOffset, v))
}

// EndOffsetGTE applies the GTE predicate on the "end_offset" field.
func EndOffsetGTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldEndOffset, v))
}

// EndOffsetLT applies the LT predicate on the "end_offset" field.
func EndOffsetLT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldEndOffset, v))
}

// EndOffsetLTE applies the LTE predicate on the "end_offset" field.
func EndOffsetLTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldEndOffset, v))
}

// EndOffsetIsNil applies the IsNil predicate on the "end_offset" field.
func EndOffsetIsNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIsNull(FieldEndOffset))
}

// EndOffsetNotNil applies the NotNil predicate on the "end_offset" field.
func EndOffsetNotNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotNull(FieldEndOffset))
}

// ChunkTypeEQ applies the EQ predicate on the "chunk_type" field.
func ChunkTypeEQ(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldChunkType, v))
}

// ChunkTypeNEQ applies the NEQ predicate on the "chunk_type" field.
func ChunkTypeNEQ(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldChunkType, v))
}

// ChunkTypeIn applies the In predicate on the "chunk_type" field.
func ChunkTypeIn(vs ...string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldChunkType, vs...))
}

// ChunkTypeNotIn applies the NotIn predicate on the "chunk_type" field.
func ChunkTypeNotIn(vs ...string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldChunkType, vs...))
}

// ChunkTypeGT applies the GT predicate on the "chunk_type" field.
func ChunkTypeGT(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldChunkType, v))
}

// ChunkTypeGTE applies the GTE predicate on the "chunk_type" field.
func ChunkTypeGTE(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldChunkType, v))
}

// ChunkTypeLT applies the LT predicate on the "chunk_type" field.
func ChunkTypeLT(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldChunkType, v))
}

// ChunkTypeLTE applies the LTE predicate on the "chunk_type" field.
func ChunkTypeLTE(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldChunkType, v))
}

// ChunkTypeContains applies the Contains predicate on the "chunk_type" field.
func ChunkTypeContains(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldContains(FieldChunkType, v))
}

// ChunkTypeHasPrefix applies the HasPrefix predicate on the "chunk_type" field.
func ChunkTypeHasPrefix(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldHasPrefix(FieldChunkType, v))
}

// ChunkTypeHasSuffix applies the HasSuffix predicate on the "chunk_type" field.
func ChunkTypeHasSuffix(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldHasSuffix(FieldChunkType, v))
}

// ChunkTypeEqualFold applies the EqualFold predicate on the "chunk_type" field.
func ChunkTypeEqualFold(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEqualFold(FieldChunkType, v))
}

// ChunkTypeContainsFold applies the ContainsFold predicate on the "chunk_type" field.
func ChunkTypeContainsFold(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldContainsFold(FieldChunkType, v))
}

// ParentChunkIndexEQ applies the EQ predicate on the "parent_chunk_index" field.
func ParentChunkIndexEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldParentChunkIndex, v))
}

// ParentChunkIndexNEQ applies the NEQ predicate on the "parent_chunk_index" field.
func ParentChunkIndexNEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldParentChunkIndex, v))
}

// ParentChunkIndexIn applies the In predicate on the "parent_chunk_index" field.
func ParentChunkIndexIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldParentChunkIndex, vs...))
}

// ParentChunkIndexNotIn applies the NotIn predicate on the "parent_chunk_index" field.
func ParentChunkIndexNotIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldParentChunkIndex, vs...))
}

// ParentChunkIndexGT applies the GT predicate on the "parent_chunk_index" field.
func ParentChunkIndexGT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldParentChunkIndex, v))
}

// ParentChunkIndexGTE applies the GTE predicate on the "parent_chunk_index" field.
func ParentChunkIndexGTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldParentChunkIndex, v))
}

// ParentChunkIndexLT applies the LT predicate on the "parent_chunk_index" field.
func ParentChunkIndexLT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldParentChunkIndex, v))
}

// ParentChunkIndexLTE applies the LTE predicate on the "parent_chunk_index" field.
func ParentChunkIndexLTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldParentChunkIndex, v))
}

// ParentChunkIndexIsNil applies the IsNil predicate on the "parent_chunk_index" field.
func ParentChunkIndexIsNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIsNull(FieldParentChunkIndex))
}

// ParentChunkIndexNotNil applies the NotNil predicate on the "parent_chunk_index" field.
func ParentChunkIndexNotNil() predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotNull(FieldParentChunkIndex))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldContainsFold(FieldText, v))
}

// CharCountEQ applies the EQ predicate on the "char_count" field.
func CharCountEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldCharCount, v))
}

// CharCountNEQ applies the NEQ predicate on the "char_count" field.
func CharCountNEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldCharCount, v))
}

// CharCountIn applies the In predicate on the "char_count" field.
func CharCountIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldCharCount, vs...))
}

// CharCountNotIn applies the NotIn predicate on the "char_count" field.
func CharCountNotIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldCharCount, vs...))
}

// CharCountGT applies the GT predicate on the "char_count" field.
func CharCountGT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldCharCount, v))
}

// CharCountGTE applies the GTE predicate on the "char_count" field.
func CharCountGTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldCharCount, v))
}

// CharCountLT applies the LT predicate on the "char_count" field.
func CharCountLT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldCharCount, v))
}

// CharCountLTE applies the LTE predicate on the "char_count" field.
func CharCountLTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldCharCount, v))
}

// TokenEstimateEQ applies the EQ predicate on the "token_estimate" field.
func TokenEstimateEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldTokenEstimate, v))
}

// TokenEstimateNEQ applies the NEQ predicate on the "token_estimate" field.
func TokenEstimateNEQ(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldTokenEstimate, v))
}

// TokenEstimateIn applies the In predicate on the "token_estimate" field.
func TokenEstimateIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldTokenEstimate, vs...))
}

// TokenEstimateNotIn applies the NotIn predicate on the "token_estimate" field.
func TokenEstimateNotIn(vs ...int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldTokenEstimate, vs...))
}

// TokenEstimateGT applies the GT predicate on the "token_estimate" field.
func TokenEstimateGT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldTokenEstimate, v))
}

// TokenEstimateGTE applies the GTE predicate on the "token_estimate" field.
func TokenEstimateGTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldTokenEstimate, v))
}

// TokenEstimateLT applies the LT predicate on the "token_estimate" field.
func TokenEstimateLT(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldTokenEstimate, v))
}

// TokenEstimateLTE applies the LTE predicate on the "token_estimate" field.
func TokenEstimateLTE(v int) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldTokenEstimate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KBDocumentChunk) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KBDocumentChunk) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KBDocumentChunk) predicate.KBDocumentChunk {
	return predicate.KBDocumentChunk(sql.NotPredicates(p))
}
