// Code generated by ent, DO NOT EDIT.

package assistantoperatorskill

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldDescription, v))
}

// BodyMd applies equality check predicate on the "body_md" field. It's identical to BodyMdEQ.
func BodyMd(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldBodyMd, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldVersion, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldStatus, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLTE(FieldUserID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldContainsFold(FieldDescription, v))
}

// BodyMdEQ applies the EQ predicate on the "body_md" field.
func BodyMdEQ(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldBodyMd, v))
}

// BodyMdNEQ applies the NEQ predicate on the "body_md" field.
func BodyMdNEQ(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNEQ(FieldBodyMd, v))
}

// BodyMdIn applies the In predicate on the "body_md" field.
func BodyMdIn(vs ...string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldIn(FieldBodyMd, vs...))
}

// BodyMdNotIn applies the NotIn predicate on the "body_md" field.
func BodyMdNotIn(vs ...string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNotIn(FieldBodyMd, vs...))
}

// BodyMdGT applies the GT predicate on the "body_md" field.
func BodyMdGT(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGT(FieldBodyMd, v))
}

// BodyMdGTE applies the GTE predicate on the "body_md" field.
func BodyMdGTE(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGTE(FieldBodyMd, v))
}

// BodyMdLT applies the LT predicate on the "body_md" field.
func BodyMdLT(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLT(FieldBodyMd, v))
}

// BodyMdLTE applies the LTE predicate on the "body_md" field.
func BodyMdLTE(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLTE(FieldBodyMd, v))
}

// BodyMdContains applies the Contains predicate on the "body_md" field.
func BodyMdContains(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldContains(FieldBodyMd, v))
}

// BodyMdHasPrefix applies the HasPrefix predicate on the "body_md" field.
func BodyMdHasPrefix(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldHasPrefix(FieldBodyMd, v))
}

// BodyMdHasSuffix applies the HasSuffix predicate on the "body_md" field.
func BodyMdHasSuffix(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldHasSuffix(FieldBodyMd, v))
}

// BodyMdEqualFold applies the EqualFold predicate on the "body_md" field.
func BodyMdEqualFold(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEqualFold(FieldBodyMd, v))
}

// BodyMdContainsFold applies the ContainsFold predicate on the "body_md" field.
func BodyMdContainsFold(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldContainsFold(FieldBodyMd, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLTE(FieldVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldContainsFold(FieldStatus, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AssistantOperatorSkill) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AssistantOperatorSkill) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AssistantOperatorSkill) predicate.AssistantOperatorSkill {
	return predicate.AssistantOperatorSkill(sql.NotPredicates(p))
}
