// Code generated by ent, DO NOT EDIT.

package siteaboutprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Ciao1019/Petrichor/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldID, id))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldDisplayName, v))
}

// RoleTitle applies equality check predicate on the "role_title" field. It's identical to RoleTitleEQ.
func RoleTitle(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldRoleTitle, v))
}

// Intro applies equality check predicate on the "intro" field. It's identical to IntroEQ.
func Intro(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldIntro, v))
}

// ExpertiseJSON applies equality check predicate on the "expertise_json" field. It's identical to ExpertiseJSONEQ.
func ExpertiseJSON(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldExpertiseJSON, v))
}

// ToolkitJSON applies equality check predicate on the "toolkit_json" field. It's identical to ToolkitJSONEQ.
func ToolkitJSON(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldToolkitJSON, v))
}

// Quote applies equality check predicate on the "quote" field. It's identical to QuoteEQ.
func Quote(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldQuote, v))
}

// AccentsJSON applies equality check predicate on the "accents_json" field. It's identical to AccentsJSONEQ.
func AccentsJSON(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldAccentsJSON, v))
}

// ContactText applies equality check predicate on the "contact_text" field. It's identical to ContactTextEQ.
func ContactText(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldContactText, v))
}

// ContactLabel applies equality check predicate on the "contact_label" field. It's identical to ContactLabelEQ.
func ContactLabel(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldContactLabel, v))
}

// ContactHref applies equality check predicate on the "contact_href" field. It's identical to ContactHrefEQ.
func ContactHref(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldContactHref, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContainsFold(FieldDisplayName, v))
}

// RoleTitleEQ applies the EQ predicate on the "role_title" field.
func RoleTitleEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldRoleTitle, v))
}

// RoleTitleNEQ applies the NEQ predicate on the "role_title" field.
func RoleTitleNEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldRoleTitle, v))
}

// RoleTitleIn applies the In predicate on the "role_title" field.
func RoleTitleIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldRoleTitle, vs...))
}

// RoleTitleNotIn applies the NotIn predicate on the "role_title" field.
func RoleTitleNotIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldRoleTitle, vs...))
}

// RoleTitleGT applies the GT predicate on the "role_title" field.
func RoleTitleGT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldRoleTitle, v))
}

// RoleTitleGTE applies the GTE predicate on the "role_title" field.
func RoleTitleGTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldRoleTitle, v))
}

// RoleTitleLT applies the LT predicate on the "role_title" field.
func RoleTitleLT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldRoleTitle, v))
}

// RoleTitleLTE applies the LTE predicate on the "role_title" field.
func RoleTitleLTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldRoleTitle, v))
}

// RoleTitleContains applies the Contains predicate on the "role_title" field.
func RoleTitleContains(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContains(FieldRoleTitle, v))
}

// RoleTitleHasPrefix applies the HasPrefix predicate on the "role_title" field.
func RoleTitleHasPrefix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasPrefix(FieldRoleTitle, v))
}

// RoleTitleHasSuffix applies the HasSuffix predicate on the "role_title" field.
func RoleTitleHasSuffix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasSuffix(FieldRoleTitle, v))
}

// RoleTitleEqualFold applies the EqualFold predicate on the "role_title" field.
func RoleTitleEqualFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEqualFold(FieldRoleTitle, v))
}

// RoleTitleContainsFold applies the ContainsFold predicate on the "role_title" field.
func RoleTitleContainsFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContainsFold(FieldRoleTitle, v))
}

// IntroEQ applies the EQ predicate on the "intro" field.
func IntroEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldIntro, v))
}

// IntroNEQ applies the NEQ predicate on the "intro" field.
func IntroNEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldIntro, v))
}

// IntroIn applies the In predicate on the "intro" field.
func IntroIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldIntro, vs...))
}

// IntroNotIn applies the NotIn predicate on the "intro" field.
func IntroNotIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldIntro, vs...))
}

// IntroGT applies the GT predicate on the "intro" field.
func IntroGT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldIntro, v))
}

// IntroGTE applies the GTE predicate on the "intro" field.
func IntroGTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldIntro, v))
}

// IntroLT applies the LT predicate on the "intro" field.
func IntroLT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldIntro, v))
}

// IntroLTE applies the LTE predicate on the "intro" field.
func IntroLTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldIntro, v))
}

// IntroContains applies the Contains predicate on the "intro" field.
func IntroContains(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContains(FieldIntro, v))
}

// IntroHasPrefix applies the HasPrefix predicate on the "intro" field.
func IntroHasPrefix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasPrefix(FieldIntro, v))
}

// IntroHasSuffix applies the HasSuffix predicate on the "intro" field.
func IntroHasSuffix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasSuffix(FieldIntro, v))
}

// IntroEqualFold applies the EqualFold predicate on the "intro" field.
func IntroEqualFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEqualFold(FieldIntro, v))
}

// IntroContainsFold applies the ContainsFold predicate on the "intro" field.
func IntroContainsFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContainsFold(FieldIntro, v))
}

// ExpertiseJSONEQ applies the EQ predicate on the "expertise_json" field.
func ExpertiseJSONEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldExpertiseJSON, v))
}

// ExpertiseJSONNEQ applies the NEQ predicate on the "expertise_json" field.
func ExpertiseJSONNEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldExpertiseJSON, v))
}

// ExpertiseJSONIn applies the In predicate on the "expertise_json" field.
func ExpertiseJSONIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldExpertiseJSON, vs...))
}

// ExpertiseJSONNotIn applies the NotIn predicate on the "expertise_json" field.
func ExpertiseJSONNotIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldExpertiseJSON, vs...))
}

// ExpertiseJSONGT applies the GT predicate on the "expertise_json" field.
func ExpertiseJSONGT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldExpertiseJSON, v))
}

// ExpertiseJSONGTE applies the GTE predicate on the "expertise_json" field.
func ExpertiseJSONGTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldExpertiseJSON, v))
}

// ExpertiseJSONLT applies the LT predicate on the "expertise_json" field.
func ExpertiseJSONLT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldExpertiseJSON, v))
}

// ExpertiseJSONLTE applies the LTE predicate on the "expertise_json" field.
func ExpertiseJSONLTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldExpertiseJSON, v))
}

// ExpertiseJSONContains applies the Contains predicate on the "expertise_json" field.
func ExpertiseJSONContains(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContains(FieldExpertiseJSON, v))
}

// ExpertiseJSONHasPrefix applies the HasPrefix predicate on the "expertise_json" field.
func ExpertiseJSONHasPrefix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasPrefix(FieldExpertiseJSON, v))
}

// ExpertiseJSONHasSuffix applies the HasSuffix predicate on the "expertise_json" field.
func ExpertiseJSONHasSuffix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasSuffix(FieldExpertiseJSON, v))
}

// ExpertiseJSONEqualFold applies the EqualFold predicate on the "expertise_json" field.
func ExpertiseJSONEqualFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEqualFold(FieldExpertiseJSON, v))
}

// ExpertiseJSONContainsFold applies the ContainsFold predicate on the "expertise_json" field.
func ExpertiseJSONContainsFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContainsFold(FieldExpertiseJSON, v))
}

// ToolkitJSONEQ applies the EQ predicate on the "toolkit_json" field.
func ToolkitJSONEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldToolkitJSON, v))
}

// ToolkitJSONNEQ applies the NEQ predicate on the "toolkit_json" field.
func ToolkitJSONNEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldToolkitJSON, v))
}

// ToolkitJSONIn applies the In predicate on the "toolkit_json" field.
func ToolkitJSONIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldToolkitJSON, vs...))
}

// ToolkitJSONNotIn applies the NotIn predicate on the "toolkit_json" field.
func ToolkitJSONNotIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldToolkitJSON, vs...))
}

// ToolkitJSONGT applies the GT predicate on the "toolkit_json" field.
func ToolkitJSONGT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldToolkitJSON, v))
}

// ToolkitJSONGTE applies the GTE predicate on the "toolkit_json" field.
func ToolkitJSONGTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldToolkitJSON, v))
}

// ToolkitJSONLT applies the LT predicate on the "toolkit_json" field.
func ToolkitJSONLT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldToolkitJSON, v))
}

// ToolkitJSONLTE applies the LTE predicate on the "toolkit_json" field.
func ToolkitJSONLTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldToolkitJSON, v))
}

// ToolkitJSONContains applies the Contains predicate on the "toolkit_json" field.
func ToolkitJSONContains(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContains(FieldToolkitJSON, v))
}

// ToolkitJSONHasPrefix applies the HasPrefix predicate on the "toolkit_json" field.
func ToolkitJSONHasPrefix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasPrefix(FieldToolkitJSON, v))
}

// ToolkitJSONHasSuffix applies the HasSuffix predicate on the "toolkit_json" field.
func ToolkitJSONHasSuffix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasSuffix(FieldToolkitJSON, v))
}

// ToolkitJSONEqualFold applies the EqualFold predicate on the "toolkit_json" field.
func ToolkitJSONEqualFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEqualFold(FieldToolkitJSON, v))
}

// ToolkitJSONContainsFold applies the ContainsFold predicate on the "toolkit_json" field.
func ToolkitJSONContainsFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContainsFold(FieldToolkitJSON, v))
}

// QuoteEQ applies the EQ predicate on the "quote" field.
func QuoteEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldQuote, v))
}

// QuoteNEQ applies the NEQ predicate on the "quote" field.
func QuoteNEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldQuote, v))
}

// QuoteIn applies the In predicate on the "quote" field.
func QuoteIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldQuote, vs...))
}

// QuoteNotIn applies the NotIn predicate on the "quote" field.
func QuoteNotIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldQuote, vs...))
}

// QuoteGT applies the GT predicate on the "quote" field.
func QuoteGT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldQuote, v))
}

// QuoteGTE applies the GTE predicate on the "quote" field.
func QuoteGTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldQuote, v))
}

// QuoteLT applies the LT predicate on the "quote" field.
func QuoteLT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldQuote, v))
}

// QuoteLTE applies the LTE predicate on the "quote" field.
func QuoteLTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldQuote, v))
}

// QuoteContains applies the Contains predicate on the "quote" field.
func QuoteContains(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContains(FieldQuote, v))
}

// QuoteHasPrefix applies the HasPrefix predicate on the "quote" field.
func QuoteHasPrefix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasPrefix(FieldQuote, v))
}

// QuoteHasSuffix applies the HasSuffix predicate on the "quote" field.
func QuoteHasSuffix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasSuffix(FieldQuote, v))
}

// QuoteEqualFold applies the EqualFold predicate on the "quote" field.
func QuoteEqualFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEqualFold(FieldQuote, v))
}

// QuoteContainsFold applies the ContainsFold predicate on the "quote" field.
func QuoteContainsFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContainsFold(FieldQuote, v))
}

// AccentsJSONEQ applies the EQ predicate on the "accents_json" field.
func AccentsJSONEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldAccentsJSON, v))
}

// AccentsJSONNEQ applies the NEQ predicate on the "accents_json" field.
func AccentsJSONNEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldAccentsJSON, v))
}

// AccentsJSONIn applies the In predicate on the "accents_json" field.
func AccentsJSONIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldAccentsJSON, vs...))
}

// AccentsJSONNotIn applies the NotIn predicate on the "accents_json" field.
func AccentsJSONNotIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldAccentsJSON, vs...))
}

// AccentsJSONGT applies the GT predicate on the "accents_json" field.
func AccentsJSONGT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldAccentsJSON, v))
}

// AccentsJSONGTE applies the GTE predicate on the "accents_json" field.
func AccentsJSONGTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldAccentsJSON, v))
}

// AccentsJSONLT applies the LT predicate on the "accents_json" field.
func AccentsJSONLT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldAccentsJSON, v))
}

// AccentsJSONLTE applies the LTE predicate on the "accents_json" field.
func AccentsJSONLTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldAccentsJSON, v))
}

// AccentsJSONContains applies the Contains predicate on the "accents_json" field.
func AccentsJSONContains(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContains(FieldAccentsJSON, v))
}

// AccentsJSONHasPrefix applies the HasPrefix predicate on the "accents_json" field.
func AccentsJSONHasPrefix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasPrefix(FieldAccentsJSON, v))
}

// AccentsJSONHasSuffix applies the HasSuffix predicate on the "accents_json" field.
func AccentsJSONHasSuffix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasSuffix(FieldAccentsJSON, v))
}

// AccentsJSONEqualFold applies the EqualFold predicate on the "accents_json" field.
func AccentsJSONEqualFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEqualFold(FieldAccentsJSON, v))
}

// AccentsJSONContainsFold applies the ContainsFold predicate on the "accents_json" field.
func AccentsJSONContainsFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContainsFold(FieldAccentsJSON, v))
}

// ContactTextEQ applies the EQ predicate on the "contact_text" field.
func ContactTextEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldContactText, v))
}

// ContactTextNEQ applies the NEQ predicate on the "contact_text" field.
func ContactTextNEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldContactText, v))
}

// ContactTextIn applies the In predicate on the "contact_text" field.
func ContactTextIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldContactText, vs...))
}

// ContactTextNotIn applies the NotIn predicate on the "contact_text" field.
func ContactTextNotIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldContactText, vs...))
}

// ContactTextGT applies the GT predicate on the "contact_text" field.
func ContactTextGT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldContactText, v))
}

// ContactTextGTE applies the GTE predicate on the "contact_text" field.
func ContactTextGTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldContactText, v))
}

// ContactTextLT applies the LT predicate on the "contact_text" field.
func ContactTextLT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldContactText, v))
}

// ContactTextLTE applies the LTE predicate on the "contact_text" field.
func ContactTextLTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldContactText, v))
}

// ContactTextContains applies the Contains predicate on the "contact_text" field.
func ContactTextContains(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContains(FieldContactText, v))
}

// ContactTextHasPrefix applies the HasPrefix predicate on the "contact_text" field.
func ContactTextHasPrefix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasPrefix(FieldContactText, v))
}

// ContactTextHasSuffix applies the HasSuffix predicate on the "contact_text" field.
func ContactTextHasSuffix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasSuffix(FieldContactText, v))
}

// ContactTextEqualFold applies the EqualFold predicate on the "contact_text" field.
func ContactTextEqualFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEqualFold(FieldContactText, v))
}

// ContactTextContainsFold applies the ContainsFold predicate on the "contact_text" field.
func ContactTextContainsFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContainsFold(FieldContactText, v))
}

// ContactLabelEQ applies the EQ predicate on the "contact_label" field.
func ContactLabelEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldContactLabel, v))
}

// ContactLabelNEQ applies the NEQ predicate on the "contact_label" field.
func ContactLabelNEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldContactLabel, v))
}

// ContactLabelIn applies the In predicate on the "contact_label" field.
func ContactLabelIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldContactLabel, vs...))
}

// ContactLabelNotIn applies the NotIn predicate on the "contact_label" field.
func ContactLabelNotIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldContactLabel, vs...))
}

// ContactLabelGT applies the GT predicate on the "contact_label" field.
func ContactLabelGT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldContactLabel, v))
}

// ContactLabelGTE applies the GTE predicate on the "contact_label" field.
func ContactLabelGTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldContactLabel, v))
}

// ContactLabelLT applies the LT predicate on the "contact_label" field.
func ContactLabelLT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldContactLabel, v))
}

// ContactLabelLTE applies the LTE predicate on the "contact_label" field.
func ContactLabelLTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldContactLabel, v))
}

// ContactLabelContains applies the Contains predicate on the "contact_label" field.
func ContactLabelContains(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContains(FieldContactLabel, v))
}

// ContactLabelHasPrefix applies the HasPrefix predicate on the "contact_label" field.
func ContactLabelHasPrefix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasPrefix(FieldContactLabel, v))
}

// ContactLabelHasSuffix applies the HasSuffix predicate on the "contact_label" field.
func ContactLabelHasSuffix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasSuffix(FieldContactLabel, v))
}

// ContactLabelEqualFold applies the EqualFold predicate on the "contact_label" field.
func ContactLabelEqualFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEqualFold(FieldContactLabel, v))
}

// ContactLabelContainsFold applies the ContainsFold predicate on the "contact_label" field.
func ContactLabelContainsFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContainsFold(FieldContactLabel, v))
}

// ContactHrefEQ applies the EQ predicate on the "contact_href" field.
func ContactHrefEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldContactHref, v))
}

// ContactHrefNEQ applies the NEQ predicate on the "contact_href" field.
func ContactHrefNEQ(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldContactHref, v))
}

// ContactHrefIn applies the In predicate on the "contact_href" field.
func ContactHrefIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldContactHref, vs...))
}

// ContactHrefNotIn applies the NotIn predicate on the "contact_href" field.
func ContactHrefNotIn(vs ...string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldContactHref, vs...))
}

// ContactHrefGT applies the GT predicate on the "contact_href" field.
func ContactHrefGT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldContactHref, v))
}

// ContactHrefGTE applies the GTE predicate on the "contact_href" field.
func ContactHrefGTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldContactHref, v))
}

// ContactHrefLT applies the LT predicate on the "contact_href" field.
func ContactHrefLT(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldContactHref, v))
}

// ContactHrefLTE applies the LTE predicate on the "contact_href" field.
func ContactHrefLTE(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldContactHref, v))
}

// ContactHrefContains applies the Contains predicate on the "contact_href" field.
func ContactHrefContains(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContains(FieldContactHref, v))
}

// ContactHrefHasPrefix applies the HasPrefix predicate on the "contact_href" field.
func ContactHrefHasPrefix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasPrefix(FieldContactHref, v))
}

// ContactHrefHasSuffix applies the HasSuffix predicate on the "contact_href" field.
func ContactHrefHasSuffix(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldHasSuffix(FieldContactHref, v))
}

// ContactHrefEqualFold applies the EqualFold predicate on the "contact_href" field.
func ContactHrefEqualFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEqualFold(FieldContactHref, v))
}

// ContactHrefContainsFold applies the ContainsFold predicate on the "contact_href" field.
func ContactHrefContainsFold(v string) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldContainsFold(FieldContactHref, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SiteAboutProfile) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SiteAboutProfile) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SiteAboutProfile) predicate.SiteAboutProfile {
	return predicate.SiteAboutProfile(sql.NotPredicates(p))
}
